export const pathNameDetailPage = '/ASM_HTML5CSS3/ASM/film-detail.html';
// export const pathNameDetailPage = '/ASM/film-detail.html';
export const pathnameIndexPage = '/ASM_HTML5CSS3/ASM/index.html'
// export const pathnameIndexPage = '/ASM/index.html'
export const pathnameLoginPage = '/ASM_HTML5CSS3/ASM/login.html'
// export const pathnameLoginPage = '/ASM/login.html'
export const pathNameUserPage = '/ASM_HTML5CSS3/ASM/user.html'
// export const pathNameUserPage = '/ASM/user.html'
export const pathNameWatchPage = '/ASM_HTML5CSS3/ASM/watch.html'
// export const pathNameWatchPage = '/ASM/watch.html'