export const filmsInMain = [
    {
        filmName: 'Tamako Market',
        subTitle: 'Tamako Market',
        thumbnail: 'assets/images/img-film/top film/tamakomarket.jpg',
        backgroundImg: 'https://images2.alphacoders.com/701/701413.png',
        view: 12000,
        episode: '12/12',
        urlVideo: '',
        desc: 'Tamako là học sinh cấp ba năm nhất, gia đình làm mochi(bánh gạo). Bộ phim xoay quanh câu chuyện trường lớp và làm việc của cô tại cửa hàng bánh của gia đình.',
        bookmark: true,
        type: 'Anime, Đời thường, Lạng mãn',
        slugs: ["sZAE7Xugm", "-bKQFF0fD", "ppeH_ry7j", "JbmgOfekm", "lRw85zME0", "WtTSqkYpY", "ZKFuiDhDR", "uYMrudMv8", "DHB4m-dcd", "drR73Ozg4", "IU3b2JpH_", "ZGykO1Xmm"]
    },
    {
        filmName: 'Tamako Love Story',
        subTitle: 'Tamako Love Story',
        thumbnail: 'assets/images/img-film/top film/tamakolovestory.jpg',
        backgroundImg: 'https://pic-bstarstatic.akamaized.net/ugc/081ccd56b436029508f4c315b372511bdc139fe6.png',
        view: 30000,
        episode: '01/01',
        urlVideo: '',
        desc: 'Câu chuyện tình yêu của Tamako',
        bookmark: true,
        type: 'Anime, Đời thường, Lạng mãn',
        slugs: ["JyQbD4yfB"]
    },
    {
        filmName: 'Thanh Gươm Diệt Quỷ',
        subTitle: 'Kimetsu No Yaiba ss2: Yuukaku-hen',
        thumbnail: 'assets/images/kimetsu-no-yaiba-ss2-thanh-guom-diet-quy-phan-2-1-250x350.jpg.webp',
        backgroundImg: 'https://file.hstatic.net/1000231532/file/r_kimetsu_no_yaiba_-_the_hinokami_chronicles_ra_mat_trailer_cot_truyen_d82208c8197542a9a9db3506b45bc944.jpg',
        view: 97000,
        episode: '11/??',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: true,
        type: 'Anime, Hành động, Shounen, Siêu nhiên, Viễn tưởng',
        slugs: ["jDfmDW5B6", "K6P662qca", "51EQG9rrQ", "R6cILrKvv", "RZQFH5XOp", "bMHw5OjbH", "hJ2nIbs02", "hIouytgpG", "VDsN9VHBih", "9aCu_vUxJ", "z5GeOXnom"]
    },
    {
        filmName: 'Độc Bộ Tiêu Dao',
        subTitle: 'Độc Bộ Tiêu Dao (2020)',
        thumbnail: 'assets/images/img-film/top film/ĐỘC BỘ TIÊU DAO.jpg',
        backgroundImg: 'https://i.ytimg.com/vi/CgUf-l6cwik/maxresdefault.jpg',
        view: 43000,
        episode: '177/???',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: true,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["Y6zUF_KgQ", "15HN_zEJw", "-8D6qWg-V4", "JtKr2rlvo", "qh5sC8Bh2", "h-vJ96DpJ", "hf8X9CZ0p", "sMs38nkgGx", "971K77KLb", "7keTwhPbs", "2TP4bwCiO", "XVQIPKQie", "20mVrbElh", "dCZSoNcQa", "9dK7_XRjx", "uC_FjEeMx2", "vncx084pL", "FFnQOovble", "uELSuMvxk", "_89TG110P"]
    },
    {
        filmName: 'Chân Võ Đỉnh Phong',
        subTitle: 'Chân Võ Đỉnh Phong (2021)',
        thumbnail: 'assets/images/img-film/top film/CHÂN VÕ ĐỈNH PHONG.jpg',
        backgroundImg: 'https://media.voocdn.com/media/image/id/61d5a6610df938bc4232bd0e_720x',
        view: 35000,
        episode: '13/??',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: true,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["nmqgb9wsS0", "INwUdi7Hq", "oFylRKxeX", "9LATpI30C", "DiMCpjqkJ", "UzGQ4XoKM", "BmTcxGSGT", "KQIRq7ciy", "YhDWlc-cs", "mOtOpMNht", "WIanHTrfy", "cWe2H81sx", "m7WGESPlv"]
    },
    {
        filmName: 'CUE!',
        subTitle: 'Cue! (2022)',
        thumbnail: 'assets/images/img-film/top film/CUE!.jpg',
        backgroundImg: 'https://wallpaperaccess.com/full/24539.jpg',
        view: 35000,
        episode: '04/??',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: false,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["IAgnLYgU", "_low3x02D", "w9-179InV", "zHmoJ19V"]
    },
    {
        filmName: "Dolls' Frontline",
        subTitle: "Girls' Frontline (2022)",
        thumbnail: "assets/images/img-film/top film/DOLLS' FRONTLINE.jpg",
        backgroundImg: 'https://i.pinimg.com/564x/60/c7/af/60c7af896ec257874789dbb6fc031e34.jpg',
        view: 57000,
        episode: '04/??',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: true,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["PdL-T2rwA", "8aNVMGIIRO", "YE96qlGDO", "W9pNgqIEUW"]
    },
    {
        filmName: 'Hồi Ký Vanitas',
        subTitle: 'Vanitas no Carte - The Case Study of Vanitas (2021)',
        thumbnail: 'assets/images/img-film/top film/HỒI KÍ VANITAS.jpg',
        backgroundImg: 'https://ecdn.game4v.com/g4v-content/uploads/2021/12/11080606/The-Case-Study-of-Vanitas-part-2-2-game4v-1639184762-96.png',
        view: 49000,
        episode: '15/24',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: true,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["miPhf8v8B", "anKXetNy9", "_JYgRvoiy"]
    },
    {
        filmName: 'Karakai Jouzu No Takagi-San 3',
        subTitle: 'Karakai Jouzu no Takagi-san Third Season, Teasing Master Takagi-san(2022)',
        thumbnail: 'assets/images/img-film/top film/KARAKAI JOUZU NO TAKAGI-SAN 3.jpg',
        backgroundImg: 'https://wallpaperspeed.id/wp-content/uploads/2022/03/Karakai-Jouzu-no-Takagi-san-3-09-49.jpg',
        view: 52000,
        episode: '04/??',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: false,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["InPBuWq0c", "PJeF_FMc", "19HKLXnx6", "XfT4KnlQY"]
    },
    {
        filmName: 'Maiko-San Chi No Makanai-San',
        subTitle: 'The caterer at the Maiko Manor, Kiyo in Kyoto: From the Maiko House (2021)',
        thumbnail: 'assets/images/img-film/top film/MAIKO-SAN CHI NO MAKANAI-SAN.jpg',
        backgroundImg: 'https://i.ytimg.com/vi_webp/SZyuBw3dhOU/maxresdefault.webp',
        view: 14000,
        episode: '12/??',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: true,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["84_wasI7F", "D90azPQIH", "uOQTqAbmB", "eqQiilsv6", "SnZ2My5Dm", "594ewvh9U", "UJ5XWztkb", "yIJLoS0Vv", "-QnZ7q0mb", "gm_foIUD2Z", "27GF9aqFo", "v6h8f1S2t"]
    },
    {
        filmName: 'Nghịch Thiên Chí Tôn',
        subTitle: 'Nghịch Thiên Chí Tôn (2021)',
        thumbnail: 'assets/images/img-film/top film/NGHỊCH THIÊN CHÍ TÔN.jpg',
        backgroundImg: "https://allimages.sgp1.digitaloceanspaces.com/tintapchicom/2021/08/Nghich-Thien-Chi-Ton-Tap-11-Vietsub-Thuyet-Minh.jpg",
        view: 98000,
        episode: '62/??',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: false,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["yUDFmuLe3", "jFzMq-INs", "w-HeuQkTJ", "ypP5G47WE", "mpn9Cls4e", "RYFaP-9_M"]
    },
    {
        filmName: 'Ousama Ranking',
        subTitle: 'King Ranking',
        thumbnail: 'assets/images/img-film/top film/OUSAMA RANKING.jpg',
        backgroundImg: 'https://cdn.wallpapersafari.com/70/65/km02En.png',
        view: 39000,
        episode: '15/23',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: true,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["-33BrvPZ2", "kY3cK1Cmm", "E2XVXs5vn", "IeVZqjho", "tehOa_ZWM", "Prjub2gHu", "hewiTmMqt", "wAXHOSPfm", "wVN7VN9bV"]
    },
    {
        filmName: 'Platinum End',
        subTitle: 'Platinum End (2021)',
        thumbnail: 'assets/images/img-film/top film/PLATINUM END.jpg',
        backgroundImg: 'https://images7.alphacoders.com/117/thumbbig-1172743.webp',
        view: 26000,
        episode: '16/24',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: false,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["Pnq_X-rbO", "CHA80_zRe", "UPzimYESu", "YQ5yu_dNq"]
    },
    {
        filmName: 'Saiyuuki Reload: Zeroin',
        subTitle: 'Saiyuuki Reload: Even a Worm Arc (2022)',
        thumbnail: 'assets/images/img-film/top film/SAIYUUKI RELOAD ZEROIN.jpg',
        backgroundImg: 'https://i0.wp.com/omnitos.com/wp-content/uploads/2022/01/Saiyuuki-Reload-Zeroin-Episode-3.jpg',
        view: 37000,
        episode: '04/??',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: true,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["J_vPPFTiM", "CB7UzvEru", "W_UEcZ-Ar", "6p7shwNwAy", "HLyj03PES", "1Z8qNZAUO", "tc2UoagHe", "xjKEJtpQe", "sRm3e-pCS6", "ojXVx6J_", "kzosIraDu", "RPjVSqyal", "wWk2rXGIQ"]
    },
    {
        filmName: 'Shingeki No Kyojin-The Final Season Part 2',
        subTitle: 'Shingeki no Kyojin Season 4, Attack on Titan Season 4 (2022)',
        thumbnail: 'assets/images/img-film/top film/SHINGEKI NO KYOJIN-THE FINAL SEASON PART 2.jpg',
        backgroundImg: 'https://animecorner.me/wp-content/uploads/2021/11/attack-on-titan-final-season-visual.png?ezimgfmt=ng%3Awebp%2Fngcb21%2Frs%3Adevice%2Frscb21-1',
        view: 90000,
        episode: '03/??',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: false,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["R4MVqnpPh", "QEeqrnFO0", "ivkvp6ZC_R", "kKCOFXbf_", "Wlc7v_GC9", "nfkBiYDZt", "svzR7d _hy", "X7UeKtugw", "YwrdoVGs0", "qr2UwUrbb", "qT33PmnHmX", "my3ErMI5F"]
    },
    {
        filmName: 'Slow Loop',
        subTitle: 'Slow Loop (2022)',
        thumbnail: 'assets/images/img-film/top film/SLOW LOOP.jpg',
        backgroundImg: 'https://images3.alphacoders.com/121/thumb-1920-1213192.jpg',
        view: 30000,
        episode: '04/??',
        urlVideo: '',
        desc: "Khi Hiyori⁠ - một cô gái trẻ có người cha quá cố đã dạy cho cô niềm vui của việc câu cá - - ra khơi một thời gian một mình, cô chưa bao giờ nghĩ rằng mình sẽ gặp một cô gái khác ở đó.Sau một thời gian, cô gái này⁠ tên là Koharu⁠ và cô ấy kết thúc câu cá và nấu ăn cùng nhau, và họ đã tìm hiểu nhau một chút trong thời gian đó. Trong khoảng thời gian ngắn ngủi bên nhau, Koharu phát hiện ra rằng lý do Hiyori đi ra biển vào ngày hôm đó là vì cô ấy do dự trong việc gặp gỡ gia đình mới của mình vào tối hôm đó. Nhưng thật là trùng hợp! Koharu cũng sẽ gặp gia đình mới của cô ấy vào tối nay! 'Không.Không thể là ngẫu nhiên ...' Cùng nhau theo dõi hai 'chị em' này và cuộc sống mới của họ!",
        bookmark: true,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["JXRkTXL7F", "iN6wPW7giv", "Rplr6x5kQ", "oEESmywyw", "iplp3sV0F", "4EhEf_FGI", "TceEwd_TCM", "M9yBo5Q3H", "wsd1tcM8c", "R_oc1T4cL", "dsu5UEAPD", "HxsKVU2YPg"]
    },
    {
        filmName: 'Thiếu Niên Ca Hành 2',
        subTitle: 'Thiếu Niên Ca Hành 2 (2021)',
        thumbnail: 'assets/images/img-film/top film/THIẾU NIÊN CA HÀNH 2.jpg',
        backgroundImg: 'https://ecdn.game4v.com/g4v-content/uploads/2021/06/gam4v-thieu-nien-ca-hanh.jpg',
        view: 96000,
        episode: '18/??',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: false,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["MaRiHIADa", "Vnb-RON0Uy", "yh-bH0Em7G", "P08zsp7Ch", "EePzF_k9g", "Nsaagg79e", "QMMTjSDcb"]
    },
    {
        filmName: 'Yêu Thần Ký',
        subTitle: 'Yêu Thần Ký (2017)',
        thumbnail: 'assets/images/img-film/top film/YÊU THẦN KÝ.jpg',
        backgroundImg: 'https://zingaudio.net/wp-content/uploads/2020/10/yeu-than-ky.jpg',
        view: 46000,
        episode: '201/???',
        urlVideo: '',
        desc: 'Không phải là quốc gia có những bộ phim hoạt hình xuất sắc nhất của điện ảnh châu Á nhưng chắc chắn trung quốc đang ngày càng cho thấy sự phát triển rất mạnh mẽ về thể loại này khi ngày càng có nhiều những tác phẩm chất lượng cả về nội dung lẫn đồ họa, trong đó những tựa phim cổ trang, kiếm hiệp được xây dựng công phu cùng những nhân vật “đẹp như mơ” thì khó có nước nào theo kịp mà Yêu Thần Ký là một ví dụ. Phát hành vào năm 2017, phim được làm dựa trên một cuốn truyện rất nổi tiếng cùng tên của tác giả Đạp Tuyết Động Mạn, mặc cho việc lên sóng chậm cùng thời lượng siêu ngắn nhưng Yao Shen Ji vẫn đủ sức làm điên đảo nhiều khán giả mê hoạt hình Việt Nam',
        bookmark: true,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["2EIYiLp9I", "j19H0noAo", "QSnq3LQzD", "vruasAPKP", "ptyMmsUsl", "YchFRPfXQ", "GXa34Tm-n", "efmPzEcZ6", "B_gsec-L2", "ISwKMDR1h"]
    },
    {
        filmName: 'Đấu Phá Thương Khung OVA',
        subTitle: 'Đấu Phá Thương Khung OVA (2021)',
        thumbnail: 'assets/images/img-film/top film/ĐẤU PHÁ THƯƠNG KHUNG OVA.jpg',
        backgroundImg: 'https://ecdn.game4v.com/g4v-content/uploads/2021/07/game4v-11.jpg',
        view: 41000,
        episode: '13/13',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: true,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["uv-KUszRii", "qsISLasWz", "TDhWyQBu30", "jiYKSETKy", "tcoJzT5Ci", "qCrmw5nPo", "JnCDeHtBR", "vZqCX7Ezt", "ENTNdkFK5", "Ok43a44SN", "5F2FwEOz", "og-PBvYpG", "tOMPiLHh"]
    },
    {
        filmName: 'Ăn Không Uổng Kể Sơn Hải Kinh',
        subTitle: 'Ăn Không Uổng Kể Sơn Hải Kinh (2021)',
        thumbnail: 'assets/images/img-film/top film/ĂN KHÔNG UỔNG KỂ SƠN HẢI KINH.jpg',
        backgroundImg: 'https://pic.bstarstatic.com/ogv/07ec26b13704e80336a427abc3cdf3c3c5ad7471.png@960w_540h_1e_1c_1f.webp',
        view: 28000,
        episode: '16/??',
        urlVideo: '',
        desc: 'Rốt cuộc thì Sơn Hải Kinh kể về cái gì? Nhà ẩm thực Ăn Không Uổng quay về thời kỳ của Sơn Hải Kinh thám hiểm những ngọn núi vùng biển mà Sơn Hải Kinh nhắc đến, vậy mà phát hiện ra mọi thứ lại thú vị đến vậy! Hoá ra Trung Quốc đã có người cá từ lâu nhưng căn bản không phải là chị gái xinh đẹp.',
        bookmark: true,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["ddSLPjemM", "LpShV50Jx", "LmkcJQUsR", "CXv03kJxn", "vjPpzk7oA", "EncjD47uM"]
    },
    {
        filmName: 'Đấu La Đại Lục',
        subTitle: 'Đấu La Đại Lục – Soul Land',
        thumbnail: 'assets/images/img-film/top film/dau-la-dai-luc-1-250x350.jpg.webp',
        backgroundImg: 'https://ss-images.saostar.vn/2020/02/24/7047527/1_fxmws8sjy0fo5ehbehzyia.png',
        view: 37000,
        episode: '193/???',
        urlVideo: '',
        desc: 'Đấu La Đại Lục là một trong những tác phẩm đặc sắc của Đường Gia Tam Thiếu. Tác phẩm thuộc thể loại Huyễn Hiệp, mang đến cho độc giả một cái nhìn, một cảm nhận mới về thế giới hiệp khách huyền ảo. Câu chuyện với nhân vật chính, con một thợ rèn, một thợ rèn trở thành tửu quỷ, vì thê tử đã mất, sẵn sàng lôi cuốn người đọc ngay từ những chương đầu tiên. Đấu La Thế Giới, một đại lục rộng lớn, cư dân đông đúc. Chức nghiệp cao quý nhất tại đây được gọi là Hồn Sư. Mỗi người sinh ra, đều có một vũ hồn bẩm sinh. Vũ hồn có thể là cái cày, cái cuốc, liêm đao… thuộc khối công cụ, một đóa hoa cúc, một cành mai… thuộc thực vật hệ, đến các vũ hồn cường đại như Tuyết Ảnh Ma Hùng, Tật Phong Ma Lang….',
        bookmark: true,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["EF6c22eqR", "6USJTAQ90", "-jRD-Db-i4", "1QI87eKp8", "m1NNc2ZNX", "-s8CZ1QF_t", "ukrqtoFQI", "k1RjW5rDZ", "U2LpYKaOkM", "AEgAywjrG", "y6luWQU4JS", "rmH5Mr2BZ", "IR978mrz1", "QnSmy3upCo", "TYq8piNeX", "nQ-kKBpr9", "6C0jrxpewP", "C9H5scLhD", "P80t6a2F2", "aVFD7w3a0N", "wjrFXIpBn"]
    },
    {
        filmName: 'Phàm Nhân Tu Tiên',
        subTitle: 'Phàm Nhân Tu Tiên - Phong Khởi Thiên Nam (2020)',
        thumbnail: 'assets/images/img-film/top film/Phàm Nhân Tu Tiên.jpg',
        backgroundImg: 'https://i.ytimg.com/vi/uZgyf0p9WXk/maxresdefault.jpg',
        view: 36000,
        episode: '34/??',
        urlVideo: '',
        desc: 'Phàm Nhân Tu Tiên - Phong Khởi Thiên Nam. Nhân vật chính của truyện, Hàn Lập sinh ra trong một gia đình nông dân nghèo, có thúc thúc là nhân viên ngoại đường của một bang phái trung lưu. Bang phái tranh chấp nên đốc rút tuyển mộ đệ tử. Hàn Lập do tư chất thấp kém, trong vài đệ tử được tuyển thì hắn chỉ vào hạng vớt vát, hay còn gọi là kí danh đệ tử. Sau đó cùng một đệ tử khác nhập vào môn đồ của một thầy thuốc của bang phái. Sư phụ này của Hàn lập tuy là một gã võ công xuất chúng chứ không phải tu tiên giả nhưng biết được công pháp tu tiên và công pháp đoạt xá (đoạt lấy thân thể của người tu tiên, người nào có linh căn thì mới có thể tu tiên).',
        bookmark: true,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["QTwrKeLB6", "aB6FxOMD3", "X62GxS-Aj", "DYJDmCSP_", "PMNM4WSUF", "_u_NYJ3PH", "WSaam0Clc", "rzRWBn2f0"]
    },
    {
        filmName: 'Vạn Giới Tiên Tung',
        subTitle: 'Vạn Giới Tiên Tung (2018)',
        thumbnail: 'assets/images/img-film/top film/Vạn Giới Tiên Tung.jpg',
        backgroundImg: 'https://static.fptplay.net/static/img/share/video/29_03_2018/van-gioi-tien-tung-229-03-2018_16g11-55.jpg',
        view: 37000,
        episode: '240/???',
        urlVideo: '',
        desc: 'Sau thành công của Yêu Thần Ký, nhà sản xuất phim đến từ trung quốc tiếp tục cho ra mắt những dự án mới hứa hẹn sẽ tiếp tục “làm mưa làm gió” tại nhiều quốc gia trong khu vực, trong đó có Việt Nam mà bằng chứng chính là bộ phim Vạn Giới Tiên Tung vốn được chuyển thể từ bộ manhua cùng tên của tác giả Đạp Tuyết Động Mạn. Phiên bản truyện tranh hiện tại đang vietsub đến chương 29 và nó cũng nhận được nhiều sự ủng hộ đến từ người đọc, đó cũng là bước đệm quan trọng để người xem đón nhận phiên bản hoạt hình với sự đầu tư công phu về kỹ thuật hình ảnh, âm thanh cũng như đồ họa 3D.',
        bookmark: true,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["bTcwJ1kqH", "ZtcUISyZD", "ZsoTAxtFo", "XjBYTMfp8", "Ort0oD9vQ", "Pc5y0KulY", "-678CF_Ne"]
    },
    {
        filmName: 'Võ Thần Chúa Tể',
        subTitle: 'Võ Thần Chúa Tể (2020)',
        thumbnail: 'assets/images/img-film/top film/Võ Thần Chúa Tể.jpg',
        backgroundImg: 'https://s2.dmcdn.net/v/T92dV1X1XpL9avReN',
        view: 59000,
        episode: '200/???',
        urlVideo: '',
        desc: 'Thiên Vũ đại lục nhất đại truyền kỳ Tần Trần, bởi vì bạn tốt phản bội bất ngờ ngã xuống Võ vực. 300 năm sau, hắn chuyển sinh ở một cái nhận hết ức hiếp vương phủ con riêng trên người, lợi dụng kiếp trước trình độ, ngưng thần công, luyện thần đan, đi ngược lên trời, quật khởi mạnh mẽ, từ đây bước lên một đoạn khiếp sợ đại lục kinh thế lữ trình.',
        bookmark: true,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["2rGgFEuMp", "qI8bFYakx", "QLtmP-Bxj", "e5VexX1V6", "IYRsIYMBp"]
    },
    {
        filmName: 'Tuyết Ưng Lĩnh Chủ Phần 3',
        subTitle: 'Tuyết Ưng Lĩnh Chủ Phần 3 (2021)',
        thumbnail: 'assets/images/img-film/top film/Tuyết Ưng Lĩnh Chủ Phần 3.jpg',
        backgroundImg: 'https://ecdn.game4v.com/g4v-content/uploads/2021/10/29151308/game4v-tuyet-ung-linh-chu-2-1635495188-92.jpg',
        view: 19000,
        episode: '06/??',
        urlVideo: '',
        desc: 'Đông Bá Liệt bỏ trốn cùng Mặc Dương Du sinh ra hai đứa con trai: Đông Bá Tuyết Ưng, Đông Bá Thanh Thạch, một nhà ẩn cư nơi quận Thanh Hà, Tuyết Ưng lĩnh. Năm Tuyết Ưng tám tuổi, hành tàng bại lộ, cữu cữu Mặc Dương Sâm cầm dụ lệnh đến bắt vợ chồng Đông Bá Liệt, Mặc Dương Du giam cầm trong biên cảnh Mặc Dương gia tộc. Vì cứu cha mẹ ra, Tuyết Ưng khổ luyện thương pháp, làm quen Dư Tĩnh Thu, trở thành Lưu Tinh kỵ sĩ. Nhưng vì đệ đệ vô ý giết chết công tử nhà giàu, khiến sát thủ của Huyết Nhận tửu quán, cao thủ Hạng Bàng của Long Sơn bảng truy sát.',
        bookmark: false,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["er9ajxA8d", "nXKrKFf35", "A6G4RR1mu", "O9Mueu-Yj", "m0sVMhvQU", "cUAZwlTAef"]
    },
    {
        filmName: 'Thôn Phệ Tinh Không',
        subTitle: 'Swallowed Star (2020)',
        thumbnail: 'assets/images/img-film/top film/Thôn Phệ Tinh Không.jpg',
        backgroundImg: 'https://img.subhay.net/date/info/Swallowed-Star-Nga-Cat-Tay-Hong-Thi-2.jpg',
        view: 21000,
        episode: '32/??',
        urlVideo: '',
        desc: 'Một ngày nọ, virus RR không rõ nguồn gốc xuất hiện trên trái đất, và thế giới dính vào thảm họa. Những con vật bị nhiễm bệnh đột biến thành những con quái vật đáng sợ và xâm chiếm hàng loạt. Thử thách mà nhân loại đã trải qua trong thời kỳ này được gọi là "Thời kỳ Niết bàn." Trong môi trường sống khắc nghiệt, thể chất của con người đang dần hoàn thiện và phát triển, xu hướng võ thuật đang lên, thể chất của con người cũng được cải thiện về chất so với trước đây. Và những người giỏi nhất trong số họ được gọi là "Warriors".',
        bookmark: true,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["ozNzjfAN1", "awCJyeHbd", "OnDqREkfV", "2FeXpzGs4", "oZuf7UQjX", "OswbwtelQ", "91PHcmPln-"]
    },
    {
        filmName: 'Koroshi Ai',
        subTitle: 'Love of Kill',
        thumbnail: 'assets/images/img-film/top film/Koroshi Ai.jpg',
        backgroundImg: 'https://www.playerone.vg/wp-content/uploads/2021/07/Koroshi-Ai-produccion.jpg',
        view: 8000,
        episode: '03/??',
        urlVideo: '',
        desc: 'Hai sát thủ đối đầu tại một "nơi làm việc". Thợ săn tiền thưởng lạnh lùng Chateau và Ryang-Ha bí ẩn và mạnh mẽ.Chateau và Ryang-Ha trở thành kẻ thù sau cuộc chiến này — ít nhất, họ nên có, nhưng vì một số lý do Ryang-Ha thích Chateau và bắt đầu theo dõi cô ấy xung quanh.Từng chút một, Chateau phát triển mối quan hệ hợp tác với Ryang-Ha, khiến cô bị cuốn vào cuộc đấu tranh chống lại các tổ chức đang săn lùng anh ta. Hơn nữa, trận chiến đó cũng liên quan đến quá khứ của cô ấy.Tại sao Ryang-Ha lại tiếp cận Chateau? Quá khứ bí mật của Chateau là gì? Hai sát thủ không khớp nhau tạo nên một bộ phim kinh dị "Sát thủ X sát thủ".Những bánh răng kỳ lạ của số phận bắt đầu chuyển động.',
        bookmark: false,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["6gRiMtD1K", "ot3J9_O-7", "CXsDsNipK", "8QVnAb3yg", "SsJidkOUA", "WOEIUSH7x", "Mfj0kMtld", "yZSKN6u9V", "ctLqT8Hqs", "7mMXhdoc-", "6vGBHOZX5", "nLLAPOx_ T"]
    },
    {
        filmName: 'Pocket Monsters: Kami To Yobareshi Arceus',
        subTitle: 'Pocket Monsters',
        thumbnail: 'assets/images/img-film/top film/Pocket Monsters Kami To Yobareshi Arceus.jpg',
        backgroundImg: 'https://media.voocdn.com/media/image/id/61f8d5ce0df93879589429ef_720x',
        view: 2000,
        episode: '02/04',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: false,
        type: 'Anime, Hành động, Shounen, Siêu nhiên, Viễn tưởng',
        slugs: ["GB1Jf4QOc", "DUzfEjTWo", "AsxYDDavlS", "ZXDEElNGX"]
    },
    {
        filmName: 'Kena No Deshi Wo Nanoru Kenja',
        subTitle: 'She Professed Herself Pupil of the Wise Man, Kendeshi',
        thumbnail: 'assets/images/img-film/top film/Kena No Deshi Wo Nanoru Kenja.jpg',
        backgroundImg: 'https://i.pinimg.com/originals/ab/a9/de/aba9de03361d8a7c5987c2d00eb65aa9.jpg',
        view: 19000,
        episode: '03/??',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: false,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["OS3_vmb6f", "LIKJTaiey_", "qoBFu0UVP", "UiPl15TZu", "aqUCISimp"]
    },
    {
        filmName: 'Sabikui Bisco',
        subTitle: 'Rust-Eater Bisco',
        thumbnail: 'assets/images/img-film/top film/Sabikui Bisco.jpg',
        backgroundImg: 'https://images8.alphacoders.com/120/1204312.jpg',
        view: 10000,
        episode: '03/??',
        urlVideo: '',
        desc: 'Thành Phố Đang Rỉ Sét - Sabikui Bisco lấy bối cảnh sau hầu tận thế tại Nhật Bản, khi một cơn gió như bệnh dịch đã thổi qua vùng đất cả khiến những người sống và đã chết trở nên rỉ sét, tất cả do một bào tử nấm gây ra. Bisco Akaboshi kẻ có biệt danh Nấm ăn thịt người và cũng là một tên tội phạm truy nã khét tiếng. Nhưng thực tế anh ta chỉ là người bảo vệ nấm để đem lại nguồn tài nguyên cho vùng đất trở lại như trước.',
        bookmark: false,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["i7fPJ-4Sa", "jLAEayGng", "KfzDf59vqs", "luwNVO6FO", "6hlSypXkN", "-7nj2zDmZ", "xDNkxP5mQ", "Oo7iohU8L", "p_FeRLuga", "8a6Za0cgC", "UCGojRjqh", "zQKPXD6mb"]
    },
    {
        filmName: 'Sabiiro No Armor: Reimei',
        subTitle: 'Rusted Armors',
        thumbnail: 'assets/images/img-film/top film/Sabiiro No Armor Reimei.jpg',
        backgroundImg: 'https://honeysanime.com/wp-content/uploads/2021/06/Sabiiro-no-Armor-Rusted-Armors-Magoichi-scaled.jpg',
        view: 2200,
        episode: '03/??',
        urlVideo: '',
        desc: 'Thời đại là thời Chiến quốc đầy biến động ở Hinomoto. Kinokuni, vùng núi và biển chưa được khám phá. Ở sâu trong rừng sâu này, có một nhóm sử dụng "Yatagarasu" làm biểu tượng cờ của họ và sử dụng súng làm vũ khí. Tên của họ là "Saikashu". Đó là "Magoichi" đến từ một đất nước xa lạ, kế thừa cái tên là người đứng đầu Saikashu. Mặt khác, "Saburo" nhanh chóng cảm nhận được dấu hiệu xâm lược từ các cường quốc châu Âu và đấu tranh để bảo vệ Hinomoto.',
        bookmark: true,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["CnNVzI5jv", "1CTNQsXs-", "497B1SiKG", "gvcFega90", "xTWwb4xRJ", "qC5aQdFql", "nGqELhxUa", "aTskjP_in", "gOZyVDbr6", "c3JetmN17", "SOciqXVDv2", "8uTeT8hcM"]
    },
    {
        filmName: 'Tabi Wa Ni',
        subTitle: 'Tabi Hani',
        thumbnail: 'assets/images/img-film/top film/Tabi Wa Ni.jpg',
        backgroundImg: 'https://gamenewsnetwork.net/wp-content/uploads/2021/12/1640271326_723_Doan-gioi-thieu-moi-da-ra-mat-Chi-tiet-phat.jpg',
        view: 283,
        episode: '05/??',
        urlVideo: '',
        desc: 'Phim Tabi wa ni 2022 vietsub thuyet minh tron bo hd xoay quanh câu chuyện kể về Akari (một học sinh trung học trầm tính, người thừa hưởng tình yêu du lịch từ chị gái, người đã chăm sóc cô thay cho cha mẹ thường xuyên vắng nhà) và Nagi (bạn học vui vẻ của Akari, người sẵn sàng tham gia bất kỳ hoạt động nào, và trở thành quan tâm đến Akari do không khí bí ẩn của cô ấy), người đi du lịch khắp Nhật Bản.',
        bookmark: false,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["qy2Vc8etj"]
    },
    {
        filmName: 'Leadale No DaiChi Nite',
        subTitle: 'World of Leadale, In the Land of Leadale',
        thumbnail: 'assets/images/img-film/top film/Leadale No DaiChi Nite.jpg',
        backgroundImg: 'https://static.zerochan.net/Leadale.no.Daichi.nite.full.3546796.jpg',
        view: 41000,
        episode: '04/??',
        urlVideo: '',
        desc: 'Khởi đầu mới ở Vùng đất quen thuộc.Sau một tai nạn kinh hoàng khiến cô phải nhờ đến sự hỗ trợ của sự sống, dấu tích tự do cuối cùng mà Keina Kagami có được là trong Thế giới VRMMORPG của Leadale. Tuy nhiên, khi thức dậy trong cơ thể của hình đại diện trò chơi của mình, Keina - bây giờ là Cayna - thấy rằng những lo lắng về cuộc sống cũ của cô dường như đã trở thành dĩ vãng, nhưng bằng cách nào đó, vùng đất mới này dường như không phải là Leadale cô ấy nhớ...',
        bookmark: false,
        type: 'Anime, Hành động, Shounen, Siêu nhiên, Viễn tưởng',
        slugs: ["hNdDMe6S-g", "y1ZhT4kBQ", "6eMvfj5Mc", "ARj4LZ-ty", "B_n0rMsvS", "vWcgZhGS7", "RxVQxJdMf", "xRrfKIL4Q", "oFH2gcoMe", "XcJ7FxFbj", "9c2sNqSB5", "-PW4j8R1X"]
    },
    {
        filmName: "Tokyo Revengers",
        subTitle: "Tokyo Revengers (2021)",
        thumbnail: "assets/images/img-film/film-category/Shounen/Tokyo Revengers.jpg",
        backgroundImg: 'https://images7.alphacoders.com/115/1155001.jpg',
        view: 881000,
        episode: '24/24',
        urlVideo: '',
        desc: 'Takemichi, thanh niên thất nghiệp còn trinh, được biết rằng người con gái đầu tiên và cũng là duy nhất cho đến bây giờ mà anh hẹn hò từ trung học đã chết. Sau một vụ tai nạn, anh ta thấy mình được quay về những ngày cấp hai. Anh ta thề sẽ thay đổi tương lai và giữ lấy người con gái ấy, để làm việc đó, anh ta quyết định sẽ vươn lên làm trùm băng đảng khét tiếng nhất ở vùng Kantou.',
        bookmark: true,
        type: 'Anime, Hành động, Shounen, Viễn tưởng',
        slugs: ["dRw9Bwocw", "Ng7DNp4Bu", "HOUft8bzv", "TfcGGojrX", "nXY-S_c_s"]
    },
    {
        filmName: "Kimetsu No Yaiba: Mugen Ressha-hen",
        subTitle: "Kimetsu no Yaiba Movie: Mugen Ressha-hen (TV) (2021)",
        thumbnail: "assets/images/img-film/film-category/Shounen/Kimetsu No Yaiba Mugen Ressha-hen.jpg",
        backgroundImg: 'https://jpsharing.net/wp-content/uploads/2021/10/Kimetsu-no-yaiba-movie-jpsharing.net-2-1.jpg',
        view: 357000,
        episode: '07/07',
        urlVideo: '',
        desc: 'Đây là bản anime truyền hình của tác phẩm điện ảnh cùng tên được ra mắt vào đầu năm. Đây là phiên bản bao gồm 7 tập với nhiều phân đoạn mới chưa xuất hiện trong bản điện ảnh đã được ra mắt trước đó. Trong phần này, Tanjiro cùng những người bạn của mình đã tới vùng đất của nhiệm vụ tiếp theo: "Chuyến tàu vô tận". Chỉ trong thời gian ngắn, nơi này đã có hơi bốn mươi người mất tích. Mặc dù đã có một số kiếm sĩ được phái ra ngoài, nhưng tất cả đều bị mất liên lạc. Nhóm Tanjiro và Zenitsu, Inosuke cùng với Nezuko họp mặt với một trong những kiếm sĩ "Trụ" mạnh nhất của Đội Diệt Quỷ là Rengoku Kyojuro. Trên chuyến tàu vô tận tiến về phía bóng tối, bọn họ sẽ phải đối mặt với những con quỷ mai phục tại đây.',
        bookmark: true,
        type: 'Anime, Hành động, Shounen, Viễn tưởng',
        slugs: ["C75Hizmgl", "Sc0EXYmc2", "KGpN9GvmW", "4ROiWutT_", "nN-rUOl2C", "3MYNsvISX", "apSruKYOM"]
    },
    {
        filmName: "Tensei Shirata Slime Datta Ken 2ND Season",
        subTitle: "Vào Ngày Đó Tôi Đã Chuyển Sinh Thành Con Slime | That Time I Got Reincarnated as a Slime Season 2, Tensura 2 (2020)",
        thumbnail: "assets/images/img-film/film-category/Shounen/TENSEI SHITARA SLIME DATTA KEN 2ND SEASON.jpg",
        backgroundImg: 'https://gamek.mediacdn.vn/133514250583805952/2021/8/30/tensei-shitara-slime-datta-ken-1-752x440-16303290822591498423164.jpg',
        view: 2162000,
        episode: '24/24',
        urlVideo: '',
        desc: 'Phần 2 của bộ phim Tensei shitara Slime Datta Ken',
        bookmark: true,
        type: 'Anime, Hành động, Shounen, Viễn tưởng, Chuyển sinh',
        slugs: ["Ay97p2kak", "sZiS4okt_", "2DeFyKn5-", "zskeRW6ZX", "9eTvwdnId", "CBtjVxOJ9", "rNe1Vw06c", "ycbzvvRf9", "6KHi0LwsE", "BjyDVerHh", "flOkVuJRI", "Dtlng_ZuH", "qrLqX-_N2", "eWWyuJbYS", "FvOxxV0DB", "tzelMrbww", "3uAfeqUFI", "SYlettdEM", "TLgFqTEY7", "ZBuzFNVIM", "XSFUuHfqJ", "ketyMUvAi", "BZZyVdshC", "-OAIPuliY", "5mejuvhV6", "pB5gdHcBF"]
    },
    {
        filmName: "Tensura Nikki Tensei Shirata Slime Datta Ken",
        subTitle: "The Slime Diaries: That Time I Got Reincarnated as a Slime (2021)",
        thumbnail: "assets/images/img-film/film-category/Shounen/TENSURA NIKKI TENSEI SHITARA SLIME DATTA KEN.jpg",
        backgroundImg: 'https://thuvienanime.com/wp-content/uploads/2021/09/Tensei-shitara-Slime-Datta-Ken.jpg',
        view: 751000,
        episode: '12/12',
        urlVideo: '',
        desc: '"Gửi nhật kí... tôi đã được tái sinh thành slime." Dù là ở thế giới khác, cuộc sống không phải lúc nào cũng bằng phẳng. Có rất nhiều việc phải làm, từ việc nuôi sống 1 cộng đồng và rèn những vật dụng thiết yếu, cũng như vui đùa... và quậy phá! Tham gia cùng Rimuru và bạn bè về cách họ tận hưởng cuộc sống hàng ngày của mình.',
        bookmark: false,
        type: 'Anime, Hành động, Shounen, Viễn tưởng, Chuyển sinh',
        slugs: ["Ci96DIR69", "btho-F4ic", "yJ7FYc4VY", "QZLRyNmph", "xdeGiI6cC", "nf8Tqs7hX", "farFCBQbN", "PjZcblAJF", "V4Ulcazni", "Qs8MApsSS", "sLwClvNKF", "UU9gkOM6d", "9MfcTjGMK", "40w9iQl8P", "Nj5ho9_c5", "rbasnSqw6", "ZReQT1EJ3", "ppfbodYy8", "e23eNR17D", "5O55UYb69", "jBLSY2nKq", "tBRYvkvkM", "mhlpcNM1L", "l9PopVnLz", "nuY-qwfyQ", "Gr4vzcxXa"]
    },
    {
        filmName: "Edens Zero",
        subTitle: "Edens Zero (2021)",
        thumbnail: "assets/images/img-film/film-category/Shounen/Edens Zero.jpg",
        backgroundImg: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3UnAUZ19_gcGZSxNa9rZHKzxRD-nUy1kETbeSx11Pt4kiK_J3F972jy2y9hTbyMtGboQ&usqp=CAU',
        view: 751000,
        episode: '23/??',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: false,
        type: 'Anime, Hành động, Shounen, Viễn tưởng',
        slugs: ["Fwvc9lDGw", "6VkBvOl_o", "TfzjHLWfk", "w3SyUBlu9", "1Bw12XeE8", "C4aoBgERi", "_-K4whEBM", "OwGN-M0dm", "PK4hn8hG5", "c1SSMhhqp", "iRiGhVjUM", "6oU2h-I5Q", "-3ThALH-X", "Ai47t_Mdo", "gEhYsWTdb", "gyWfDDPlU", "nf8BvIBRP", "iZRplroq3", "sIk4bzXD7", "prJSQFjn3", "Tcy6cKVQPH", "2hLJGGLdY", "Zlnsis5et", "P6yzPQ_W5", "RMLD2rkY9"]
    },
    {
        filmName: "Fumetsu No Anata E",
        subTitle: "Gửi em, người bất tử (2021)",
        thumbnail: "assets/images/img-film/film-category/Shounen/Fumetsu No Anata E.jpg",
        backgroundImg: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQloxU_8Q8A3MJdn2PPMt7M5ZVlGPFVSlL65wiTOhrpVSUwMPH17zh0BFXNep822IMBPgs&usqp=CAU',
        view: 650000,
        episode: '20/??',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: false,
        type: 'Anime, Hành động, Shounen, Viễn tưởng',
        slugs: ["85HLejmkd", "L52vhb0Wa", "58YgP7kmy", "1t-z-y9pQ", "TDajnM-QI", "WK17_JoEu", "EEluyaZN_", "sU1f9Q6p4p", "cWqWFgWu7", "IzVW1QC2q", "BYfGPY6UK", "8j8flEpVT", "7I3GCZI6a", "pJA0Qm_Z1", "_IJS-mtYU", "FQCgYTljm", "xaJlA7XUm", "bOQ6rvTId", "Oqun0jPl4", "SZGMUMn-5"]
    },
    {
        filmName: "Shaman King",
        subTitle: "Shaman King (2021) (2021)",
        thumbnail: "assets/images/img-film/film-category/Shounen/Shaman King.jpg",
        backgroundImg: 'https://i0.wp.com/anitrendz.net/news/wp-content/uploads/2021/06/Shaman-King-Soundtrack-scaled-e1624581333444.jpg',
        view: 595000,
        episode: '41/52',
        urlVideo: '',
        desc: 'Bản Remake bản đẹp của bộ anime đình đám Vua pháp thuật với nội dung Trong thế giới của Vua Pháp sư có những pháp sư có thể điều khiển được các linh hồn. Mỗi pháp sư có một linh hồn đi kèm để hỗ trợ. Cứ 500 năm 1 lần sẽ có một đại hội thi đấu giữa các pháp sư để chọn ra một vua pháp sư. Người này sẽ có được linh hồn vĩ đại của Trái Đất để giúp thế giới. Tuy nhiên 2 cuộc thi đấu gần đây nhất đã bị phá hoại bởi một pháp sư tên là Asakura Hao. Manta là một cậu bé đang học trung học ở Tokyo. Cậu tình cờ làm quen với Yoh, một pháp sư mới chuyển đến cùng lớp. Manta lần lượt gặp những pháp sư khác như Anna, Ryu, Tao Ren, Tao Jun. Vua Pháp sư kể về cuộc phiêu lưu của Yoh, Anna, và các bạn qua lời kể của Manta.',
        bookmark: false,
        type: 'Anime, Hành động, Shounen, Viễn tưởng',
        slugs: ["L_hU1s0pa", "s0yLbe-So", "pSbNS3BpT", "1v7PgVBC2", "9fa2cNUM6", "OvVpyEZZ8", "a3QvoJ6uB"]
    },
    {
        filmName: "Kakushigoto Movie",
        subTitle: "Hidden Things Movie (2021)",
        thumbnail: "assets/images/img-film/film-category/Shounen/Karushigoto Movie.jpg",
        backgroundImg: 'https://images5.alphacoders.com/107/1073869.jpg',
        view: 21000,
        episode: '01/01',
        urlVideo: '',
        desc: 'Phim tổng hợp của loạt phim truyền hình bao gồm những cảnh mới chưa được chuyển thể trong anime truyền hình và các góc nhìn khác nhau. Kakushi Gotou là một họa sĩ truyện tranh nổi tiếng với những tác phẩm được biết đến với nội dung không phù hợp. Vì sự kỳ lạ này, khi cô con gái Hime được sinh ra, anh đã thề sẽ giấu kín nghề của mình với cô, tin rằng cô sẽ vỡ mộng nếu phát hiện ra.',
        bookmark: true,
        type: 'Anime, Hành động, Shounen, Viễn tưởng',
        slugs: ["ZrDIdVn0V"]
    },
    {
        filmName: "Boruto: Naruto Next Generations",
        subTitle: "BORUTO -NARUTO NEXT GENERATIONS- ( Naruto Season 3) | Boruto: Naruto những thế hệ kế tiếp (2017)",
        thumbnail: "assets/images/img-film/film-category/Shounen/BORUTO NARUTO NEXT GENERATIONS.jpg",
        backgroundImg: 'https://static.ssphim.net/static/5fe2d564b3fa6403ffa11d1c/60939d111563bd83d552ae11_boruto-1.jpg',
        view: 4966000,
        episode: '234/???',
        urlVideo: '',
        desc: '',
        bookmark: true,
        type: 'Anime, Hành động, Shounen, Viễn tưởng',
        slugs: ["etUYLbPZP", "U_Pltc6dG"]
    },
    {
        filmName: "Nanatsu No Taizai Movie 2 Hikari Ni Norowareshi Mono-Tachi",
        subTitle: "Gekijouban Nanatsu no Taizai Hikari ni Norowareshi Mono-tachi, The Seven Deadly Sins the Movie: Cursed by Light (2021)",
        thumbnail: "assets/images/img-film/film-category/Shounen/NANATSU NO TAIZAI MOVIE 2 HIKARI NI NOROWARESHI MONO-TACHI.jpg",
        backgroundImg: 'https://i3.wp.com/img.bilutv.cc/film/18637/big.jpg',
        view: 80000,
        episode: '01/01',
        urlVideo: '',
        desc: 'Câu chuyện hoàn toàn mới của tác giả manga gốc Nakaba Suzuki lấy bối cảnh sau Bảy Đại Tội: Sự phán xét của Rồng.',
        bookmark: true,
        type: 'Anime, Hành động, Shounen, Viễn tưởng',
        slugs: ["JRGDAuQhB"]
    },
    {
        filmName: "Vua Hải Tặc",
        subTitle: "One Piece | Đảo Hải Tặc (1999)",
        thumbnail: "assets/images/img-film/film-category/Shounen/Vua Hải Tặc.jpg",
        backgroundImg: 'https://i.pinimg.com/originals/a2/84/29/a284294e7badfbda66fea132db44dc76.jpg',
        view: 5212000,
        episode: '1008/????',
        urlVideo: '',
        desc: '',
        bookmark: false,
        type: 'Anime, Hành động, Shounen, Viễn tưởng',
        slugs: ["eR8qNcse-"]
    },
    {
        filmName: "Dragon Ball Heroes",
        subTitle: "Dragon Ball Heroes (2018)",
        thumbnail: "assets/images/img-film/film-category/Shounen/Dragon Ball Heroes.jpg",
        backgroundImg: 'https://i.pinimg.com/originals/b8/09/20/b80920500b773a22ec8af4af240c1340.jpg',
        view: 897000,
        episode: '23/??',
        urlVideo: '',
        desc: '',
        bookmark: true,
        type: 'Anime, Hành động, Shounen, Viễn tưởng',
        slugs: ["HivXHfZfh", "qlmhLOrEU", "4YBO9DTBq", "jJYCoyhgJ", "_mdckcsRk", "qLysePF7A", "ICzlk6deA", "SDnPpMdgr", "l3C66gHC9", "WiYZcPh7S"]
    },
];

export const topView = [
    {
        filmName: "Kimetsu No Yaiba ss2: Yuukaku-hen",
        subTitle: "Kimetsu No Yaiba ss2: Yuukaku-hen",
        view: 97000,
        top1: true,
        desc: "Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ",
        bookmark: true,
        episode: "08/??",
        thumbnail: "assets/images/kimetsu-no-yaiba-ss2-thanh-guom-diet-quy-phan-2-1-250x350.jpg.webp",
        backgroundImg: "https://file.hstatic.net/1000231532/file/r_kimetsu_no_yaiba_-_the_hinokami_chronicles_ra_mat_trailer_cot_truyen_d82208c8197542a9a9db3506b45bc944.jpg",
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["jDfmDW5B6", "K6P662qca", "51EQG9rrQ", "R6cILrKvv", "RZQFH5XOp", "bMHw5OjbH", "hJ2nIbs02", "hIouytgpG", "VDsN9VHBih", "9aCu_vUxJ", "z5GeOXnom"]
    },
    {
        filmName: "Black Clover",
        subTitle: "Thế Giới Phép Thuật",
        view: 67000,
        top1: false,
        desc: "Anime Black Clover - Thế Giới Phép Thuật là 1 bộ phim thuộc thể loại phép thuật, phiêu lưu vô cùng nổi tiếng. Phim Black Clover là câu chuyện về 2 chàng trai Asta và Yuno, họ đã bị bỏ rơi cùng nhau tại cùng một nhà thờ và đã không thể tách rời kể từ đó. Khi còn trẻ, họ hứa sẽ cạnh tranh với nhau để xem ai sẽ trở thành Ma Pháp Đế tiếp theo.",
        bookmark: true,
        episode: "153/???",
        thumbnail: "https://i.pinimg.com/originals/0a/2a/e8/0a2ae87158dbd761d30dd7be5517cfff.jpg",
        backgroundImg: "https://images3.alphacoders.com/911/911611.png",
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["EOn7yukDl", "PCnmuSH0T", "klaY3n3S3K", "AyCOZHcVW", "EYLx6CuaD", "hsZY4OLWb", "u9klddoLIX", "2ciaVs8qr"]
    },
    {
        filmName: "Đấu La Đại Lục",
        subTitle: "Douluo Dalu, Combat Continent, Soul Land",
        view: 43000,
        top1: false,
        desc: "Đấu La Đại Lục là một trong những tác phẩm đặc sắc của Đường Gia Tam Thiếu. Tác phẩm thuộc thể loại Huyễn Hiệp, mang đến cho độc giả một cái nhìn, một cảm nhận mới về thế giới hiệp khách huyền ảo. Câu chuyện với nhân vật chính, con một thợ rèn, một thợ rèn trở thành tửu quỷ, vì thê tử đã mất, sẵn sàng lôi cuốn người đọc ngay từ những chương đầu tiên. Đấu La Thế Giới, một đại lục rộng lớn, cư dân đông đúc. Chức nghiệp cao quý nhất tại đây được gọi là Hồn Sư. Mỗi người sinh ra, đều có một vũ hồn bẩm sinh. Vũ hồn có thể là cái cày, cái cuốc, liêm đao… thuộc khối công cụ, một đóa hoa cúc, một cành mai… thuộc thực vật hệ, đến các vũ hồn cường đại như Tuyết Ảnh Ma Hùng, Tật Phong Ma Lang…. ",
        bookmark: true,
        episode: "215/???",
        thumbnail: "assets/images/img-film/top-view-film/dau-la-dai-luc-1-250x350.jpg.webp",
        backgroundImg: "https://ss-images.saostar.vn/2020/02/24/7047527/1_fxmws8sjy0fo5ehbehzyia.png",
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["EF6c22eqR", "6USJTAQ90", "-jRD-Db-i4", "1QI87eKp8", "m1NNc2ZNX", "-s8CZ1QF_t", "ukrqtoFQI", "k1RjW5rDZ", "U2LpYKaOkM", "AEgAywjrG", "y6luWQU4JS", "rmH5Mr2BZ", "IR978mrz1", "QnSmy3upCo", "TYq8piNeX", "nQ-kKBpr9", "6C0jrxpewP", "C9H5scLhD", "P80t6a2F2", "aVFD7w3a0N", "wjrFXIpBn"]
    },
    {
        filmName: "Doraemon New TV Series",
        subTitle: "Doremon | Chú Mèo máy thần kỳ | Mèo Máy Doraemon | Đôrêmon",
        view: 38000,
        top1: false,
        desc: "Các câu chuyện trong Doraemon thường có một công thức chung, đó là xoay quanh những rắc rối hay xảy ra với cậu bé Nobita học lớp bốn, nhân vật chính thứ nhì của bộ truyện. Doraemon có một chiếc túi thần kỳ trước bụng với đủ loại bảo bối của tương lai. Cốt truyện thường gặp nhất sẽ là Nobita trở về nhà khóc lóc với những rắc rối mà cậu gặp phải ở trường hoặc với bạn bè. Sau khi bị cậu bé van nài hoặc thúc giục, Doraemon sẽ đưa ra một bảo bối giúp Nobita giải quyết những rắc rối của mình, hoặc là để trả đũa hay khoe khoang với bạn bè của cậu. Nobita sẽ lại thường đi quá xa so với dự định ban đầu của Doraemon, thậm chí với những bảo bối mới cậu còn gặp rắc rối lớn hơn trước đó. Đôi khi những người bạn của Nobita, thường là Suneo (Xêkô) hoặc Jaian (Chaien) lại lấy trộm những bảo bối và sử dụng chúng không đúng mục đích. Tuy nhiên thường thì ở cuối mỗi câu chuyện, những ai sử dụng sai mục đích bảo bối sẽ phải chịu hậu quả do mình gây ra, và người đọc sẽ rút ra được bài học từ đó.",
        bookmark: true,
        episode: "713/???",
        thumbnail: "assets/images/img-film/top-view-film/doraemon-new-tv-series.jpg",
        backgroundImg: "https://cdn.voh.com.vn/voh/thumbnail/2022/03/12/list-15-phim-hoat-hinh-doraemon-tap-dai.jpg",
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["9g7R-S9ew", "80wizFgT3", "l62Jdq8ti"]
    },
    {
        filmName: "Arifureta Shokugyou de Sekai Saikyou 2nd Season",
        subTitle: "From Common Job Class to the Strongest in the World 2nd Season",
        view: 34000,
        top1: false,
        desc: "Mùa hai của Arifureta Shokugyou de Sekai Saikyou.",
        bookmark: true,
        episode: "12/12",
        thumbnail: "assets/images/img-film/top-view-film/arifureta-shokugyou-de-sekai-saikyou-2nd-season.jpg",
        backgroundImg: "https://www.kaorinusantara.or.id/wp-content/uploads/2019/10/arifureta.jpg",
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["HPOI_Mm4x", "Cv0qBH_Os", "ZLdwvx_Xw", "yhSx6d2Iq", "3TPqpolFE", "2L5RGxCqN", "5AwLeMBFC", "ikC7Yf0al", "nYL7E8SiCh", "_VJTjsOKy", "GsaXhD06I", "XP89rnSZo", "8jQYJIq6N"]
    },
    {
        filmName: "Naruto: Shippuuden",
        subTitle: "Naruto Hurricane Chronicles, Naruto: Sức Mạnh Vĩ Thú | Naruto Phần",
        view: 32000,
        top1: false,
        desc: "Naruto Shippuden hay còn được gọi với cái tên quen thuộc Naruto phần 2 là phần tiếp theo của bộ phim hoạt hình nổi tiếng Naruto, lấy bối cảnh hai năm rưỡi sau khi Naruto rời làng Lá. Naruto Shippuden tiếp tục theo chân chàng ninja trẻ tuổi Naruto Uzumaki trong cuộc hành trình luyện tập cực khổ để trở thành ninja giỏi nhất. Trong khi đó, Akatsuki, một tổ chức bí ẩn tập hợp những ninja phản diện tài giỏi bậc nhất, đang từng bước thực hiện kế hoạch lớn của chúng, đe dọa sự an toàn của thế giới ninja. Naruto sẽ làm gì để bảo vệ làng Lá và những người mà cậu yêu quý?",
        bookmark: true,
        episode: "500/???",
        thumbnail: "assets/images/img-film/top-view-film/naruto-shippuuden-thumbnail.jpg",
        backgroundImg: "https://cdn.tgdd.vn/2020/07/content/thumb-800x450-33.jpg",
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["hSJbpmsAP", "RqmhY7B9e", "70_TXjMQO", "bpz-z6G1P", "Y7dYqGQ27"]
    },
    {
        filmName: "Ousama Ranking",
        subTitle: "King Ranking, Bảng Xếp Hạng Quốc Vương",
        view: 32000,
        top1: false,
        desc: 'Phim xoay quanh Bojji, một hoàng tử bị điếc, bất lực, thậm chí không thể sử dụng thanh kiếm của trẻ em. Là con trai đầu lòng, anh phấn đấu hết mình và ước mơ trở thành vị vua vĩ đại nhất thế giới. Tuy nhiên, mọi người đồn thổi về anh sau lưng anh là "một hoàng tử chẳng ra gì" và "không thể nào anh có thể làm vua được." Bojji có thể kết bạn đầu tiên của mình, "Kage" (bóng tối) —một cái bóng theo nghĩa đen trên mặt đất, người bằng cách nào đó hiểu rõ Bojji. (Kage là một người sống sót trong gia tộc sát thủ Kage đã bị xóa sổ. Không còn là một kẻ giết người, Kage giờ đây kiếm sống bằng cách ăn trộm.) với cuộc gặp gỡ định mệnh của mình với Kage.',
        bookmark: true,
        episode: "15/23",
        thumbnail: "assets/images/img-film/top-view-film/bang-xep-hang-quoc-vuong-ousama-ranking-thumbnail.jpg",
        backgroundImg: "https://cdn.wallpapersafari.com/70/65/km02En.png",
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["-33BrvPZ2", "kY3cK1Cmm", "E2XVXs5vn", "IeVZqjho", "tehOa_ZWM", "Prjub2gHu", "hewiTmMqt", "wAXHOSPfm", "wVN7VN9bV"]
    },
    {
        filmName: "Shikkakumon no Saikyou Kenja",
        subTitle: "The Strongest Sage of Disqualified Crest, Shikkakumon no Saikyokenja",
        view: 30000,
        top1: false,
        desc: "Sức mạnh của anh ta bị giới hạn bởi huy hiệu ma thuật mà anh ta có từ khi được sinh ra, Mathias, nhà hiền triết mạnh nhất thế giới, quyết định phải chuyển sinh để trở thành người mạnh nhất. Khi tái sinh là một cậu bé, Mathias rất vui mừng khi phát hiện ra rằng cậu được sinh ra với huy hiệu tối ưu để chiến đấu bằng phép thuật trong lần thử đầu tiên! Thật không may, thế giới mà anh ấy sinh ra có những tiêu chuẩn cực kỳ kém về phép thuật, và mọi người đều nghĩ rằng anh ấy vẫn là kẻ thất bại! Bây giờ Mathias phải chứng minh mọi người sai… theo phong cách của nhà hiền triết mạnh nhất thế giới!",
        bookmark: false,
        episode: "12/12",
        thumbnail: "assets/images/img-film/top-view-film/shikkakumon-no-saikyou-kenja-thumbnail.jpg",
        backgroundImg: "https://truyengihot.net/uploads/anime/cover_1641666501.jpg",
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["L2XHCumZi", "CjP4HJaG8", "u1ROrN995", "plPrFb4K_", "n5s85i68y", "pjE4A6sSh", "U4x1kV176", "DAjuUokMg", "tbcvYScmq", "pzu-Ds4BF", "KPyiRvubu", "0hXGEmTov"]
    },
    {
        filmName: "Sono Bisque Doll wa Koi wo Suru",
        subTitle: "My Dress-Up Darling, Sono Kisekae Ningyou wa Koi wo Suru",
        view: 29000,
        top1: false,
        desc: "Wakana Gojou là một thằng giai tân mười lăm tuổi, người bị sang chấn tâm lí trong quá khứ do niềm đam mê của mình. Sự cố đó đã để lại dấu ấn cho anh khiến anh trở thành một người ẩn dật xã hội. Cho đến một ngày, anh đã gặp phải Kitagawa, một gyaru hòa đồng, hoàn toàn trái ngược với anh. Họ sớm chia sẻ niềm đam mê của họ với nhau mà dẫn đến mối quan hệ kỳ quặc của họ.",
        bookmark: true,
        episode: "12/12",
        thumbnail: "assets/images/img-film/top-view-film/sono-bisque-doll-wa-koi-wo-suru-thumbnail.jpg",
        backgroundImg: "https://static.lag.vn/upload/news/21/12/06/anime-Sono-Bisque-Doll-Wa-Koi-Wo-Suru_DGYY.jpg?w=800&encoder=wic&subsampling=444",
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["-FSCpm7IT", "NzsgioFCd", "DsEN-tmoP", "2FOqcWCyz", "9VpUoiZ4_", "s90j7Og-9", "t64tJF-fIG", "50zcBdNno", "hbruYEm3F", "ZEjkow23w", "0Ytojtyav", "qvOWAVf_m"]
    },
    {
        filmName: "King's Raid: Ishi Wo Tsugumono-Tachi",
        subTitle: "Kings Raid: Ishi wo Tsugumono-tachi (2020)",
        view: 26000,
        top1: false,
        desc: "Đã 100 năm kể từ khi vua Kyle chôn cất Ang Mundo. Bây giờ trong thời kỳ hòa bình, hiệp sĩ tập sự Kasel tận hưởng cuộc sống của mình mà không cần lo lắng. Tuy nhiên, số phận của anh ta bắt đầu thay đổi, với tin tức về những con quỷ xuất hiện xâm chiếm khu phố. Được hướng dẫn bởi một người đàn ông thông thái, Kasel tìm thấy những người bạn mà anh có thể dựa vào và bắt đầu sứ mệnh tìm kiếm thánh kiếm, có khả năng tiêu diệt kẻ thù mới tìm thấy của mình.",
        bookmark: false,
        episode: "26/26",
        thumbnail: "assets/images/img-film/top-view-film/King raid.jpg",
        backgroundImg: "https://i.ytimg.com/vi/7FyrUKmai3I/maxresdefault.jpg",
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["O8sXI9KMJ", "hSg8Wn_3v", "3Ccfbrpf5G", "_r3TUdmRI", "PbVIty2lXm", "6PmzBEJkX3", "u4oOAXDDo", "KcfYzNPzgb", "_P_bCI6Vf", "LRGQZXXPO"]
    },
]

export const topComment = [
    {
        filmName: "Black Clover",
        subTitle: "Thế Giới Phép Thuật",
        comment: 980,
        top1: true,
        desc: "Anime Black Clover - Thế Giới Phép Thuật là 1 bộ phim thuộc thể loại phép thuật, phiêu lưu vô cùng nổi tiếng. Phim Black Clover là câu chuyện về 2 chàng trai Asta và Yuno, họ đã bị bỏ rơi cùng nhau tại cùng một nhà thờ và đã không thể tách rời kể từ đó. Khi còn trẻ, họ hứa sẽ cạnh tranh với nhau để xem ai sẽ trở thành Ma Pháp Đế tiếp theo.",
        bookmark: true,
        episode: "153/???",
        thumbnail: "https://i.pinimg.com/originals/0a/2a/e8/0a2ae87158dbd761d30dd7be5517cfff.jpg",
        backgroundImg: "https://images3.alphacoders.com/911/911611.png",
        type: 'Phiêu lưu',
        slugs: ["EOn7yukDl", "PCnmuSH0T", "klaY3n3S3K", "AyCOZHcVW", "EYLx6CuaD", "hsZY4OLWb", "u9klddoLIX", "2ciaVs8qr"]
    },
    {
        filmName: "Jujutsu Kaisen",
        subTitle: "Sorcery Fight (2020)",
        comment: 920,
        top1: false,
        desc: "Thiếu niên Itadori Yuuji, mang năng lực thể chất phi thường, trải qua cuộc sống học sinh cấp 3 bình thường, nhưng đến một ngày vì cứu bạn bè bị đe doạ bởi “lời nguyền”, cậu đã nuốt chú vật đặc cấp - “Ngón tay của Ryomen Sukuna” và để cho lời nguyền trú ngụ trong linh hồn mình.",
        bookmark: true,
        episode: "10/24",
        thumbnail: "assets/images/img-film/top-film-cmt/Jujutsu Kaisen.jpg",
        backgroundImg: "https://i0.wp.com/dmtalkies.com/wp-content/uploads/2021/08/ezgif-1-078409066a3b-compressed-1.jpg?fit=1200%2C674&ssl=1",
        type: 'Hành động, viễn tưởng',
        slugs: ["vzx7upXjI", "Orblz3UMi", "8Mg4jiydc3", "1DwbDQ6jW", "EU254N30N", "jgJott7Vp", "9SZ2Wrkzp", "8RrS7EexA", "7Z58yujDZ", "55E9n0tp7", "S0eMaIvpXb", "ylh4jv0H6", "uo4CK2QSt", "g8ThUQLPG", "bVxucyl9H", "0aX8FIZKL", "EHfeiOymd", "VNPJjd2kH", "95LCcfcQ8g", "JBQL9HoKc", "R8F4wtY7Q", "WOdbw850R", "yyg4x_nsT", "nztQ4xk048"]
    },
    {
        filmName: "Arifureta Shokugyou De Sekai Saikyou 2nd Season",
        subTitle: "From Common Job Class to the Strongest in the World 2nd Season",
        comment: 900,
        top1: false,
        desc: "Mùa hai của Arifureta Shokugyou de Sekai Saikyou.",
        bookmark: true,
        episode: "12/12",
        thumbnail: "assets/images/img-film/top-film-cmt/arifureta-shokugyou-de-sekai-saikyou-2nd-season.jpg",
        backgroundImg: "https://www.kaorinusantara.or.id/wp-content/uploads/2019/10/arifureta.jpg",
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["HPOI_Mm4x", "Cv0qBH_Os", "ZLdwvx_Xw", "yhSx6d2Iq", "3TPqpolFE", "2L5RGxCqN", "5AwLeMBFC", "ikC7Yf0al", "nYL7E8SiCh", "_VJTjsOKy", "GsaXhD06I", "XP89rnSZo", "8jQYJIq6N"]
    },
    {
        filmName: "Ousama Ranking",
        subTitle: "King Ranking, Bảng Xếp Hạng Quốc Vương",
        comment: 500,
        top1: false,
        desc: 'Phim xoay quanh Bojji, một hoàng tử bị điếc, bất lực, thậm chí không thể sử dụng thanh kiếm của trẻ em. Là con trai đầu lòng, anh phấn đấu hết mình và ước mơ trở thành vị vua vĩ đại nhất thế giới. Tuy nhiên, mọi người đồn thổi về anh sau lưng anh là "một hoàng tử chẳng ra gì" và "không thể nào anh có thể làm vua được." Bojji có thể kết bạn đầu tiên của mình, "Kage" (bóng tối) —một cái bóng theo nghĩa đen trên mặt đất, người bằng cách nào đó hiểu rõ Bojji. (Kage là một người sống sót trong gia tộc sát thủ Kage đã bị xóa sổ. Không còn là một kẻ giết người, Kage giờ đây kiếm sống bằng cách ăn trộm.) với cuộc gặp gỡ định mệnh của mình với Kage.',
        bookmark: true,
        episode: "15/23",
        thumbnail: "assets/images/img-film/top-film-cmt/bang-xep-hang-quoc-vuong-ousama-ranking-thumbnail.jpg",
        backgroundImg: "https://cdn.wallpapersafari.com/70/65/km02En.png",
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["-33BrvPZ2", "kY3cK1Cmm", "E2XVXs5vn", "IeVZqjho", "tehOa_ZWM", "Prjub2gHu", "hewiTmMqt", "wAXHOSPfm", "wVN7VN9bV"]
    },
    {
        filmName: "Majo No Tabitabi",
        subTitle: "The Journey of Elaina | Wandering Witch: The Journey of Elaina (2020)",
        comment: 480,
        top1: false,
        desc: "Ngày xửa ngày xưa, xưa ơi là xưa, xưa thiệt là xưa, có một cô phù thủy tên là Elaina, cô chính là người sẽ có cuộc hành trình đi xuyên thế giới. Trên đường đi, cô sẽ gặp rất nhiều người, nhiều nơi. Từ một vùng đất đầy phù thủy đến một nơi có những tên khổng lồ cuồng cơ bắp nhưng trong mỗi cuộc gặp gỡ, Elaina sẽ bắt tay trở thành một phần nhỏ trong câu chuyện của họ và về thế giới riêng của cô nàng bé nhỏ này.",
        bookmark: false,
        episode: "12/12",
        thumbnail: "assets/images/img-film/top-film-cmt/Majo No Tabitabi.jpg",
        backgroundImg: "https://i.ytimg.com/vi/SpTgCQGWqqc/maxresdefault.jpg",
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["HFnLY4mr2", "wAOL5eE17", "wAOL5eE17", "iylJ_ciIh", "gYUEFumo8"]
    },
    {
        filmName: "Doraemon New Tv Series",
        subTitle: "Doremon | Chú Mèo máy thần kỳ | Mèo Máy Doraemon | Đôrêmon",
        comment: 200,
        top1: false,
        desc: "Các câu chuyện trong Doraemon thường có một công thức chung, đó là xoay quanh những rắc rối hay xảy ra với cậu bé Nobita học lớp bốn, nhân vật chính thứ nhì của bộ truyện. Doraemon có một chiếc túi thần kỳ trước bụng với đủ loại bảo bối của tương lai. Cốt truyện thường gặp nhất sẽ là Nobita trở về nhà khóc lóc với những rắc rối mà cậu gặp phải ở trường hoặc với bạn bè. Sau khi bị cậu bé van nài hoặc thúc giục, Doraemon sẽ đưa ra một bảo bối giúp Nobita giải quyết những rắc rối của mình, hoặc là để trả đũa hay khoe khoang với bạn bè của cậu. Nobita sẽ lại thường đi quá xa so với dự định ban đầu của Doraemon, thậm chí với những bảo bối mới cậu còn gặp rắc rối lớn hơn trước đó. Đôi khi những người bạn của Nobita, thường là Suneo (Xêkô) hoặc Jaian (Chaien) lại lấy trộm những bảo bối và sử dụng chúng không đúng mục đích. Tuy nhiên thường thì ở cuối mỗi câu chuyện, những ai sử dụng sai mục đích bảo bối sẽ phải chịu hậu quả do mình gây ra, và người đọc sẽ rút ra được bài học từ đó.",
        bookmark: true,
        episode: "713/???",
        thumbnail: "assets/images/img-film/top-film-cmt/doraemon-new-tv-series.jpg",
        backgroundImg: "https://cdn.voh.com.vn/voh/thumbnail/2022/03/12/list-15-phim-hoat-hinh-doraemon-tap-dai.jpg",
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["9g7R-S9ew", "80wizFgT3", "l62Jdq8ti"]
    },
    {
        filmName: "Đấu La Đại Lục",
        subTitle: "Douluo Dalu, Combat Continent, Soul Land",
        comment: 190,
        top1: false,
        desc: "Đấu La Đại Lục là một trong những tác phẩm đặc sắc của Đường Gia Tam Thiếu. Tác phẩm thuộc thể loại Huyễn Hiệp, mang đến cho độc giả một cái nhìn, một cảm nhận mới về thế giới hiệp khách huyền ảo. Câu chuyện với nhân vật chính, con một thợ rèn, một thợ rèn trở thành tửu quỷ, vì thê tử đã mất, sẵn sàng lôi cuốn người đọc ngay từ những chương đầu tiên. Đấu La Thế Giới, một đại lục rộng lớn, cư dân đông đúc. Chức nghiệp cao quý nhất tại đây được gọi là Hồn Sư. Mỗi người sinh ra, đều có một vũ hồn bẩm sinh. Vũ hồn có thể là cái cày, cái cuốc, liêm đao… thuộc khối công cụ, một đóa hoa cúc, một cành mai… thuộc thực vật hệ, đến các vũ hồn cường đại như Tuyết Ảnh Ma Hùng, Tật Phong Ma Lang….",
        bookmark: true,
        episode: "215/???",
        thumbnail: "assets/images/img-film/top-film-cmt/dau-la-dai-luc-1-250x350.jpg.webp",
        backgroundImg: "https://ss-images.saostar.vn/2020/02/24/7047527/1_fxmws8sjy0fo5ehbehzyia.png",
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["EF6c22eqR", "6USJTAQ90", "-jRD-Db-i4", "1QI87eKp8", "m1NNc2ZNX", "-s8CZ1QF_t", "ukrqtoFQI", "k1RjW5rDZ", "U2LpYKaOkM", "AEgAywjrG", "y6luWQU4JS", "rmH5Mr2BZ", "IR978mrz1", "QnSmy3upCo", "TYq8piNeX", "nQ-kKBpr9", "6C0jrxpewP", "C9H5scLhD", "P80t6a2F2", "aVFD7w3a0N", "wjrFXIpBn"]
    },
    {
        filmName: "Adachi To Shimamura",
        subTitle: "Adachi and Shimamura (2020)",
        comment: 100,
        top1: false,
        desc: "Tầng hai của phòng tập thể dục ― đây là nơi chúng tôi luôn gặp nhau. Đó là giờ học, nhưng tất nhiên, không có bất kỳ lớp học nào diễn ra ở một nơi như thế này.Đây là nơi tôi và Shimamura trở thành bạn của nhau. Chúng tôi đã đi chơi ở đây ― nói về các chương trình truyền hình và nấu ăn, chơi bóng bàn ... Đây là nơi chúng tôi nuôi dưỡng tình bạn của mình.Cúi đầu vào tường, tôi khẽ thở dài.Cảm giác này là gì? Hôm qua, tôi đã mơ thấy tôi và Shimamura hôn nhau.Không phải tôi như vậy. Tôi chắc rằng Shimamura cũng không.",
        bookmark: false,
        episode: " 12/12",
        thumbnail: "assets/images/img-film/top-film-cmt/Adachi To Shimamura.jpg",
        backgroundImg: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTyBFak6Vy0vpaUiBn-S6qEl7APLmgu7JND_w&usqp=CAU",
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["5j6HLqmW6", "wHCsLDDYag", "O0cAdpOo5", "yVp70A2qjZ", "O6gsTiDQk", "vvY0Q0iYf"]
    },
    {
        filmName: "King's Raid: Ishi Wo Tsugumono-Tachi",
        subTitle: "Kings Raid: Ishi wo Tsugumono-tachi (2020)",
        comment: 86,
        top1: false,
        desc: "Đã 100 năm kể từ khi vua Kyle chôn cất Ang Mundo. Bây giờ trong thời kỳ hòa bình, hiệp sĩ tập sự Kasel tận hưởng cuộc sống của mình mà không cần lo lắng. Tuy nhiên, số phận của anh ta bắt đầu thay đổi, với tin tức về những con quỷ xuất hiện xâm chiếm khu phố. Được hướng dẫn bởi một người đàn ông thông thái, Kasel tìm thấy những người bạn mà anh có thể dựa vào và bắt đầu sứ mệnh tìm kiếm thánh kiếm, có khả năng tiêu diệt kẻ thù mới tìm thấy của mình.",
        bookmark: false,
        episode: "26/26",
        thumbnail: "assets/images/img-film/top-film-cmt/King raid.jpg",
        backgroundImg: "https://i.ytimg.com/vi/7FyrUKmai3I/maxresdefault.jpg",
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["O8sXI9KMJ", "hSg8Wn_3v", "3Ccfbrpf5G", "_r3TUdmRI", "PbVIty2lXm", "6PmzBEJkX3", "u4oOAXDDo", "KcfYzNPzgb", "_P_bCI6Vf", "LRGQZXXPO"]
    },
]

export const filmsTrend = [
    {
        filmName: 'Thanh Gươm Diệt Quỷ',
        subTitle: 'Kimetsu No Yaiba ss2: Yuukaku-hen',
        thumbnail: 'assets/images/kimetsu-no-yaiba-ss2-thanh-guom-diet-quy-phan-2-1-250x350.jpg.webp',
        backgroundImg: 'https://file.hstatic.net/1000231532/file/r_kimetsu_no_yaiba_-_the_hinokami_chronicles_ra_mat_trailer_cot_truyen_d82208c8197542a9a9db3506b45bc944.jpg',
        view: 97000,
        episode: '11/??',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: true,
        type: 'Anime, Hành động, Shounen, Siêu nhiên, Viễn tưởng',
        slugs: ["jDfmDW5B6", "K6P662qca", "51EQG9rrQ", "R6cILrKvv", "RZQFH5XOp", "bMHw5OjbH", "hJ2nIbs02", "hIouytgpG", "VDsN9VHBih", "9aCu_vUxJ", "z5GeOXnom"]
    },
    {
        filmName: 'Độc Bộ Tiêu Dao',
        subTitle: 'Độc Bộ Tiêu Dao (2020)',
        thumbnail: 'assets/images/img-film/top film/ĐỘC BỘ TIÊU DAO.jpg',
        backgroundImg: 'https://i.ytimg.com/vi/CgUf-l6cwik/maxresdefault.jpg',
        view: 43000,
        episode: '177/???',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: true,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["Y6zUF_KgQ", "15HN_zEJw", "-8D6qWg-V4", "JtKr2rlvo", "qh5sC8Bh2", "h-vJ96DpJ", "hf8X9CZ0p", "sMs38nkgGx", "971K77KLb", "7keTwhPbs", "2TP4bwCiO", "XVQIPKQie", "20mVrbElh", "dCZSoNcQa", "9dK7_XRjx", "uC_FjEeMx2", "vncx084pL", "FFnQOovble", "uELSuMvxk", "_89TG110P"]
    },
    {
        filmName: 'Nghịch Thiên Chí Tôn',
        subTitle: 'Nghịch Thiên Chí Tôn (2021)',
        thumbnail: 'assets/images/img-film/top film/NGHỊCH THIÊN CHÍ TÔN.jpg',
        backgroundImg: "https://allimages.sgp1.digitaloceanspaces.com/tintapchicom/2021/08/Nghich-Thien-Chi-Ton-Tap-11-Vietsub-Thuyet-Minh.jpg",
        view: 98000,
        episode: '62/??',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: false,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["yUDFmuLe3", "jFzMq-INs", "w-HeuQkTJ", "ypP5G47WE", "mpn9Cls4e", "RYFaP-9_M"]
    },
    {
        filmName: 'Ousama Ranking',
        subTitle: 'King Ranking',
        thumbnail: 'assets/images/img-film/top film/OUSAMA RANKING.jpg',
        backgroundImg: 'https://cdn.wallpapersafari.com/70/65/km02En.png',
        view: 39000,
        episode: '15/23',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: true,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["-33BrvPZ2", "kY3cK1Cmm", "E2XVXs5vn", "IeVZqjho", "tehOa_ZWM", "Prjub2gHu", "hewiTmMqt", "wAXHOSPfm", "wVN7VN9bV"]
    },
    {
        filmName: 'Kena No Deshi Wo Nanoru Kenja',
        subTitle: 'She Professed Herself Pupil of the Wise Man, Kendeshi',
        thumbnail: 'assets/images/img-film/top film/Kena No Deshi Wo Nanoru Kenja.jpg',
        backgroundImg: 'https://i.pinimg.com/originals/ab/a9/de/aba9de03361d8a7c5987c2d00eb65aa9.jpg',
        view: 19000,
        episode: '03/??',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: false,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["OS3_vmb6f", "LIKJTaiey_", "qoBFu0UVP", "UiPl15TZu", "aqUCISimp"]
    },
    {
        filmName: 'Sabikui Bisco',
        subTitle: 'Rust-Eater Bisco',
        thumbnail: 'assets/images/img-film/top film/Sabikui Bisco.jpg',
        backgroundImg: 'https://images8.alphacoders.com/120/1204312.jpg',
        view: 10000,
        episode: '03/??',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: false,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["i7fPJ-4Sa", "jLAEayGng", "KfzDf59vqs", "luwNVO6FO", "6hlSypXkN", "-7nj2zDmZ", "xDNkxP5mQ", "Oo7iohU8L", "p_FeRLuga", "8a6Za0cgC", "UCGojRjqh", "zQKPXD6mb"]
    },
    {
        filmName: 'Sabiiro No Armor: Reimei',
        subTitle: 'Rusted Armors',
        thumbnail: 'assets/images/img-film/top film/Sabiiro No Armor Reimei.jpg',
        backgroundImg: 'https://honeysanime.com/wp-content/uploads/2021/06/Sabiiro-no-Armor-Rusted-Armors-Magoichi-scaled.jpg',
        view: 2200,
        episode: '03/??',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: true,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["CnNVzI5jv", "1CTNQsXs-", "497B1SiKG", "gvcFega90", "xTWwb4xRJ", "qC5aQdFql", "nGqELhxUa", "aTskjP_in", "gOZyVDbr6", "c3JetmN17", "SOciqXVDv2", "8uTeT8hcM"]
    },
    {
        filmName: 'Tabi Wa Ni',
        subTitle: 'Tabi Hani',
        thumbnail: 'assets/images/img-film/top film/Tabi Wa Ni.jpg',
        backgroundImg: 'https://gamenewsnetwork.net/wp-content/uploads/2021/12/1640271326_723_Doan-gioi-thieu-moi-da-ra-mat-Chi-tiet-phat.jpg',
        view: 283,
        episode: '05/??',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: false,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["qy2Vc8etj"]
    }
];

export const showTimes = [
    {
        filmName: 'Chân Võ Đỉnh Phong',
        subTitle: 'Chân Võ Đỉnh Phong (2021)',
        thumbnail: 'assets/images/img-film/top film/CHÂN VÕ ĐỈNH PHONG.jpg',
        backgroundImg: 'https://media.voocdn.com/media/image/id/61d5a6610df938bc4232bd0e_720x',
        view: 35000,
        episode: '12/??',
        date: 'monday',
        newEpisode: 13,
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: true,
        type: 'Anime, Hành động, Shounen, Siêu nhiên, Viễn tưởng',
        slugs: ["nmqgb9wsS0", "INwUdi7Hq", "oFylRKxeX", "9LATpI30C", "DiMCpjqkJ", "UzGQ4XoKM", "BmTcxGSGT", "KQIRq7ciy", "YhDWlc-cs", "mOtOpMNht", "WIanHTrfy", "cWe2H81sx", "m7WGESPlv"]
    },
    {
        filmName: "Dolls' Frontline",
        subTitle: "Girls' Frontline (2022)",
        thumbnail: "assets/images/img-film/top film/DOLLS' FRONTLINE.jpg",
        backgroundImg: 'https://i.pinimg.com/564x/60/c7/af/60c7af896ec257874789dbb6fc031e34.jpg',
        view: 57000,
        episode: '03/??',
        date: 'monday',
        newEpisode: 4,
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: false,
        type: 'Anime, Hành động, Shounen, Siêu nhiên, Viễn tưởng',
        slugs: ["PdL-T2rwA", "8aNVMGIIRO", "YE96qlGDO", "W9pNgqIEUW"]
    },
    {
        filmName: 'Platinum End',
        subTitle: 'Platinum End (2021)',
        thumbnail: 'assets/images/img-film/top film/PLATINUM END.jpg',
        backgroundImg: 'https://images7.alphacoders.com/117/thumbbig-1172743.webp',
        view: 26000,
        episode: '15/24',
        date: 'monday',
        newEpisode: 16,
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: true,
        type: 'Anime, Hành động, Shounen, Siêu nhiên, Viễn tưởng',
        slugs: ["Pnq_X-rbO", "CHA80_zRe", "UPzimYESu", "YQ5yu_dNq"]
    },
    {
        filmName: 'Thanh Gươm Diệt Quỷ',
        subTitle: 'Kimetsu No Yaiba ss2: Yuukaku-hen',
        thumbnail: 'assets/images/kimetsu-no-yaiba-ss2-thanh-guom-diet-quy-phan-2-1-250x350.jpg.webp',
        backgroundImg: 'https://file.hstatic.net/1000231532/file/r_kimetsu_no_yaiba_-_the_hinokami_chronicles_ra_mat_trailer_cot_truyen_d82208c8197542a9a9db3506b45bc944.jpg',
        view: 97000,
        episode: '11/??',
        date: 'tuesday',
        newEpisode: 10,
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: true,
        type: 'Anime, Hành động, Shounen, Siêu nhiên, Viễn tưởng',
        slugs: ["jDfmDW5B6", "K6P662qca", "51EQG9rrQ", "R6cILrKvv", "RZQFH5XOp", "bMHw5OjbH", "hJ2nIbs02", "hIouytgpG", "VDsN9VHBih", "9aCu_vUxJ", "z5GeOXnom"]
    },
    {
        filmName: 'Độc Bộ Tiêu Dao',
        subTitle: 'Độc Bộ Tiêu Dao (2020)',
        thumbnail: 'assets/images/img-film/top film/ĐỘC BỘ TIÊU DAO.jpg',
        backgroundImg: 'https://i.ytimg.com/vi/CgUf-l6cwik/maxresdefault.jpg',
        view: 43000,
        episode: '117/??',
        date: 'tuesday',
        newEpisode: 118,
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: true,
        type: 'Anime, Hành động, Shounen, Siêu nhiên, Viễn tưởng',
        slugs: ["Y6zUF_KgQ", "15HN_zEJw", "-8D6qWg-V4", "JtKr2rlvo", "qh5sC8Bh2", "h-vJ96DpJ", "hf8X9CZ0p", "sMs38nkgGx", "971K77KLb", "7keTwhPbs", "2TP4bwCiO", "XVQIPKQie", "20mVrbElh", "dCZSoNcQa", "9dK7_XRjx", "uC_FjEeMx2", "vncx084pL", "FFnQOovble", "uELSuMvxk", "_89TG110P"]
    },
    {
        filmName: 'Hồi Ký Vanitas',
        subTitle: 'Vanitas no Carte - The Case Study of Vanitas (2021)',
        thumbnail: 'assets/images/img-film/top film/HỒI KÍ VANITAS.jpg',
        backgroundImg: 'https://ecdn.game4v.com/g4v-content/uploads/2021/12/11080606/The-Case-Study-of-Vanitas-part-2-2-game4v-1639184762-96.png',
        view: 43000,
        episode: '14/24',
        date: 'wednesday',
        newEpisode: 15,
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: true,
        type: 'Anime, Hành động, Shounen, Siêu nhiên, Viễn tưởng',
        slugs: ["miPhf8v8B", "anKXetNy9", "_JYgRvoiy"]
    },
    {
        filmName: 'Maiko-San Chi No Makanai-San',
        subTitle: 'The caterer at the Maiko Manor, Kiyo in Kyoto: From the Maiko House (2021)',
        thumbnail: 'assets/images/img-film/top film/MAIKO-SAN CHI NO MAKANAI-SAN.jpg',
        backgroundImg: 'https://i.ytimg.com/vi_webp/SZyuBw3dhOU/maxresdefault.webp',
        view: 14000,
        episode: '11/??',
        date: 'wednesday',
        newEpisode: 12,
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: false,
        type: 'Anime, Hành động, Shounen, Siêu nhiên, Viễn tưởng',
        slugs: ["84_wasI7F", "D90azPQIH", "uOQTqAbmB", "eqQiilsv6", "SnZ2My5Dm", "594ewvh9U", "UJ5XWztkb", "yIJLoS0Vv", "-QnZ7q0mb", "gm_foIUD2Z", "27GF9aqFo", "v6h8f1S2t"]
    },
    {
        filmName: 'Saiyuuki Reload: Zeroin',
        subTitle: 'Saiyuuki Reload: Even a Worm Arc (2022)',
        thumbnail: 'assets/images/img-film/top film/SAIYUUKI RELOAD ZEROIN.jpg',
        backgroundImg: 'https://i0.wp.com/omnitos.com/wp-content/uploads/2022/01/Saiyuuki-Reload-Zeroin-Episode-3.jpg',
        view: 37000,
        episode: '04/??',
        date: 'wednesday',
        newEpisode: 5,
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: true,
        type: 'Anime, Hành động, Shounen, Siêu nhiên, Viễn tưởng',
        slugs: ["J_vPPFTiM", "CB7UzvEru", "W_UEcZ-Ar", "6p7shwNwAy", "HLyj03PES", "1Z8qNZAUO", "tc2UoagHe", "xjKEJtpQe", "sRm3e-pCS6", "ojXVx6J_", "kzosIraDu", "RPjVSqyal", "wWk2rXGIQ"]
    },
    {
        filmName: 'Maiko-San Chi No Makanai-San',
        subTitle: 'The caterer at the Maiko Manor, Kiyo in Kyoto: From the Maiko House (2021)',
        thumbnail: 'assets/images/img-film/top film/MAIKO-SAN CHI NO MAKANAI-SAN.jpg',
        backgroundImg: 'https://i.ytimg.com/vi_webp/SZyuBw3dhOU/maxresdefault.webp',
        view: 14000,
        episode: '12/??',
        date: 'thursday',
        newEpisode: 13,
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: false,
        type: 'Anime, Hành động, Shounen, Siêu nhiên, Viễn tưởng',
        slugs: ["84_wasI7F", "D90azPQIH", "uOQTqAbmB", "eqQiilsv6", "SnZ2My5Dm", "594ewvh9U", "UJ5XWztkb", "yIJLoS0Vv", "-QnZ7q0mb", "gm_foIUD2Z", "27GF9aqFo", "v6h8f1S2t"]
    },
    {
        filmName: 'Nghịch Thiên Chí Tôn',
        subTitle: 'Nghịch Thiên Chí Tôn (2021)',
        thumbnail: 'assets/images/img-film/top film/NGHỊCH THIÊN CHÍ TÔN.jpg',
        backgroundImg: 'https://allimages.sgp1.digitaloceanspaces.com/tintapchicom/2021/08/Nghich-Thien-Chi-Ton-Tap-11-Vietsub-Thuyet-Minh.jpg',
        view: 98000,
        episode: '61/??',
        date: 'thursday',
        newEpisode: 62,
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: false,
        type: 'Anime, Hành động, Shounen, Siêu nhiên, Viễn tưởng',
        slugs: ["yUDFmuLe3", "jFzMq-INs", "w-HeuQkTJ", "ypP5G47WE", "mpn9Cls4e", "RYFaP-9_M"]
    },
    {
        filmName: 'Saiyuuki Reload: Zeroin',
        subTitle: 'Saiyuuki Reload: Even a Worm Arc (2022)',
        thumbnail: 'assets/images/img-film/top film/SAIYUUKI RELOAD ZEROIN.jpg',
        backgroundImg: 'https://i0.wp.com/omnitos.com/wp-content/uploads/2022/01/Saiyuuki-Reload-Zeroin-Episode-3.jpg',
        view: 98000,
        episode: '04/??',
        date: 'friday',
        newEpisode: 6,
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: false,
        type: 'Anime, Hành động, Shounen, Siêu nhiên, Viễn tưởng',
        slugs: ["J_vPPFTiM", "CB7UzvEru", "W_UEcZ-Ar", "6p7shwNwAy", "HLyj03PES", "1Z8qNZAUO", "tc2UoagHe", "xjKEJtpQe", "sRm3e-pCS6", "ojXVx6J_", "kzosIraDu", "RPjVSqyal", "wWk2rXGIQ"]
    },
    {
        filmName: 'Shingeki No Kyojin-The Final Season Part 2',
        subTitle: 'Shingeki no Kyojin Season 4, Attack on Titan Season 4 (2022)',
        thumbnail: 'assets/images/img-film/top film/SHINGEKI NO KYOJIN-THE FINAL SEASON PART 2.jpg',
        backgroundImg: 'https://animecorner.me/wp-content/uploads/2021/11/attack-on-titan-final-season-visual.png?ezimgfmt=ng%3Awebp%2Fngcb21%2Frs%3Adevice%2Frscb21-1',
        view: 90000,
        episode: '03/??',
        date: 'friday',
        newEpisode: 4,
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: false,
        type: 'Anime, Hành động, Shounen, Siêu nhiên, Viễn tưởng',
        slugs: ["R4MVqnpPh", "QEeqrnFO0", "ivkvp6ZC_R", "kKCOFXbf_", "Wlc7v_GC9", "nfkBiYDZt", "svzR7d _hy", "X7UeKtugw", "YwrdoVGs0", "qr2UwUrbb", "qT33PmnHmX", "my3ErMI5F"]
    },
    {
        filmName: 'Slow Loop',
        subTitle: 'Slow Loop (2022)',
        thumbnail: 'assets/images/img-film/top film/SLOW LOOP.jpg',
        backgroundImg: 'https://images3.alphacoders.com/121/thumb-1920-1213192.jpg',
        view: 30000,
        episode: '03/??',
        date: 'friday',
        newEpisode: 4,
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: false,
        type: 'Anime, Hành động, Shounen, Siêu nhiên, Viễn tưởng',
        slugs: ["Tv41IWZm4A", "wbjdfrCCU", "Z8C2IRYh8", "vpF-A1PaeO", "exfwaB1gR", "lCVgvVzYZ", "ktl7fR8hK", "AvpfG4lKW", "z4ecSanKD", "OgXHqtKD5", "dA2uD76DD", "73OLLZpCg"]
    },
    {
        filmName: 'Thiếu Niên Ca Hành 2',
        subTitle: 'Thiếu Niên Ca Hành 2 (2021)',
        thumbnail: 'assets/images/img-film/top film/THIẾU NIÊN CA HÀNH 2.jpg',
        backgroundImg: 'https://ecdn.game4v.com/g4v-content/uploads/2021/06/gam4v-thieu-nien-ca-hanh.jpg',
        view: 96000,
        episode: '18/??',
        date: 'friday',
        newEpisode: 19,
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: false,
        type: 'Anime, Hành động, Shounen, Siêu nhiên, Viễn tưởng',
        slugs: ["MaRiHIADa", "Vnb-RON0Uy", "yh-bH0Em7G", "P08zsp7Ch", "EePzF_k9g", "Nsaagg79e", "QMMTjSDcb"]
    },
    {
        filmName: 'Yêu Thần Ký',
        subTitle: 'Yêu Thần Ký (2021)',
        thumbnail: 'assets/images/img-film/top film/YÊU THẦN KÝ.jpg',
        backgroundImg: 'https://zingaudio.net/wp-content/uploads/2020/10/yeu-than-ky.jpg',
        view: 46000,
        episode: '200/???',
        date: 'friday',
        newEpisode: 201,
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: false,
        type: 'Anime, Hành động, Shounen, Siêu nhiên, Viễn tưởng',
        slugs: ["2EIYiLp9I", "j19H0noAo", "QSnq3LQzD", "vruasAPKP", "ptyMmsUsl", "YchFRPfXQ", "GXa34Tm-n", "efmPzEcZ6", "B_gsec-L2", "ISwKMDR1h"]
    },
    {
        filmName: 'Ăn Không Uổng Kể Sơn Hải Kinh',
        subTitle: 'Ăn Không Uổng Kể Sơn Hải Kinh (2021)',
        thumbnail: 'assets/images/img-film/top film/ĂN KHÔNG UỔNG KỂ SƠN HẢI KINH.jpg',
        backgroundImg: 'https://pic.bstarstatic.com/ogv/07ec26b13704e80336a427abc3cdf3c3c5ad7471.png@960w_540h_1e_1c_1f.webp',
        view: 28000,
        date: 'saturday',
        newEpisode: 17,
        episode: '16/??',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: true,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: []
    },
    {
        filmName: 'Đấu La Đại Lục',
        subTitle: 'Đấu La Đại Lục – Soul Land',
        thumbnail: 'assets/images/img-film/top film/dau-la-dai-luc-1-250x350.jpg.webp',
        backgroundImg: 'https://ss-images.saostar.vn/2020/02/24/7047527/1_fxmws8sjy0fo5ehbehzyia.png',
        view: 37000,
        date: 'monday',
        newEpisode: 194,
        episode: '193/???',
        urlVideo: '',
        desc: 'Đấu La Đại Lục là một trong những tác phẩm đặc sắc của Đường Gia Tam Thiếu. Tác phẩm thuộc thể loại Huyễn Hiệp, mang đến cho độc giả một cái nhìn, một cảm nhận mới về thế giới hiệp khách huyền ảo. Câu chuyện với nhân vật chính, con một thợ rèn, một thợ rèn trở thành tửu quỷ, vì thê tử đã mất, sẵn sàng lôi cuốn người đọc ngay từ những chương đầu tiên. Đấu La Thế Giới, một đại lục rộng lớn, cư dân đông đúc. Chức nghiệp cao quý nhất tại đây được gọi là Hồn Sư. Mỗi người sinh ra, đều có một vũ hồn bẩm sinh. Vũ hồn có thể là cái cày, cái cuốc, liêm đao… thuộc khối công cụ, một đóa hoa cúc, một cành mai… thuộc thực vật hệ, đến các vũ hồn cường đại như Tuyết Ảnh Ma Hùng, Tật Phong Ma Lang….',
        bookmark: true,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["EF6c22eqR", "6USJTAQ90", "-jRD-Db-i4", "1QI87eKp8", "m1NNc2ZNX", "-s8CZ1QF_t", "ukrqtoFQI", "k1RjW5rDZ", "U2LpYKaOkM", "AEgAywjrG", "y6luWQU4JS", "rmH5Mr2BZ", "IR978mrz1", "QnSmy3upCo", "TYq8piNeX", "nQ-kKBpr9", "6C0jrxpewP", "C9H5scLhD", "P80t6a2F2", "aVFD7w3a0N", "wjrFXIpBn"]
    },
    {
        filmName: 'Phàm Nhân Tu Tiên',
        subTitle: 'Phàm Nhân Tu Tiên - Phong Khởi Thiên Nam (2020)',
        thumbnail: 'assets/images/img-film/top film/Phàm Nhân Tu Tiên.jpg',
        backgroundImg: 'https://i.ytimg.com/vi/uZgyf0p9WXk/maxresdefault.jpg',
        view: 36000,
        date: 'saturday',
        newEpisode: 35,
        episode: '34/??',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: true,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["QTwrKeLB6", "aB6FxOMD3", "X62GxS-Aj", "DYJDmCSP_", "PMNM4WSUF", "_u_NYJ3PH", "WSaam0Clc", "rzRWBn2f0"]
    },
    {
        filmName: 'Tuyết Ưng Lĩnh Chủ Phần 3',
        subTitle: 'Tuyết Ưng Lĩnh Chủ Phần 3 (2021)',
        thumbnail: 'assets/images/img-film/top film/Tuyết Ưng Lĩnh Chủ Phần 3.jpg',
        backgroundImg: 'https://ecdn.game4v.com/g4v-content/uploads/2021/10/29151308/game4v-tuyet-ung-linh-chu-2-1635495188-92.jpg',
        view: 19000,
        date: 'sunday',
        newEpisode: 7,
        episode: '06/??',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: false,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["er9ajxA8d", "nXKrKFf35", "A6G4RR1mu", "O9Mueu-Yj", "m0sVMhvQU", "cUAZwlTAef"]
    },
    {
        filmName: 'Thôn Phệ Tinh Không',
        subTitle: 'Swallowed Star (2020)',
        thumbnail: 'assets/images/img-film/top film/Thôn Phệ Tinh Không.jpg',
        backgroundImg: 'https://img.subhay.net/date/info/Swallowed-Star-Nga-Cat-Tay-Hong-Thi-2.jpg',
        view: 21000,
        date: 'sunday',
        newEpisode: 33,
        episode: '32/??',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: true,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["ozNzjfAN1", "awCJyeHbd", "OnDqREkfV", "2FeXpzGs4", "oZuf7UQjX", "OswbwtelQ", "91PHcmPln-"]
    },
];