export const filmsInMain = [
    {
        filmName: 'Thanh Gươm Diệt Quỷ',
        subTitle: 'Kimetsu No Yaiba ss2: Yuukaku-hen',
        thumbnail: 'assets/images/kimetsu-no-yaiba-ss2-thanh-guom-diet-quy-phan-2-1-250x350.jpg.webp',
        backgroundImg: 'https://file.hstatic.net/1000231532/file/r_kimetsu_no_yaiba_-_the_hinokami_chronicles_ra_mat_trailer_cot_truyen_d82208c8197542a9a9db3506b45bc944.jpg',
        view: 97000,
        episode: '11/??',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: true,
        type: 'Anime, Hành động, Shounen, Siêu nhiên, Viễn tưởng',
        slugs: ["jDfmDW5B6", "K6P662qca", "51EQG9rrQ", "R6cILrKvv", "RZQFH5XOp", "bMHw5OjbH", "hJ2nIbs02", "hIouytgpG", "VDsN9VHBih", "9aCu_vUxJ", "z5GeOXnom"]
    },
    {
        filmName: 'Độc Bộ Tiêu Dao',
        subTitle: 'Độc Bộ Tiêu Dao (2020)',
        thumbnail: 'assets/images/img-film/top film/ĐỘC BỘ TIÊU DAO.jpg',
        backgroundImg: 'https://i.ytimg.com/vi/CgUf-l6cwik/maxresdefault.jpg',
        view: 43000,
        episode: '177/???',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: true,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["Y6zUF_KgQ", "15HN_zEJw", "-8D6qWg-V4", "JtKr2rlvo", "qh5sC8Bh2", "h-vJ96DpJ", "hf8X9CZ0p", "sMs38nkgGx", "971K77KLb", "7keTwhPbs", "2TP4bwCiO", "XVQIPKQie", "20mVrbElh", "dCZSoNcQa", "9dK7_XRjx", "uC_FjEeMx2", "vncx084pL", "FFnQOovble", "uELSuMvxk", "_89TG110P"]
    },
    {
        filmName: 'Chân Võ Đỉnh Phong',
        subTitle: 'Chân Võ Đỉnh Phong (2021)',
        thumbnail: 'assets/images/img-film/top film/CHÂN VÕ ĐỈNH PHONG.jpg',
        backgroundImg: 'https://media.voocdn.com/media/image/id/61d5a6610df938bc4232bd0e_720x',
        view: 35000,
        episode: '13/??',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: true,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["nmqgb9wsS0", "INwUdi7Hq", "oFylRKxeX", "9LATpI30C", "DiMCpjqkJ", "UzGQ4XoKM", "BmTcxGSGT", "KQIRq7ciy", "YhDWlc-cs", "mOtOpMNht", "WIanHTrfy", "cWe2H81sx", "m7WGESPlv"]
    },
    {
        filmName: 'CUE!',
        subTitle: 'Cue! (2022)',
        thumbnail: 'assets/images/img-film/top film/CUE!.jpg',
        backgroundImg: 'https://wallpaperaccess.com/full/24539.jpg',
        view: 35000,
        episode: '04/??',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: false,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["IAgnLYgU", "_low3x02D", "w9-179InV", "zHmoJ19V"]
    },
    {
        filmName: "Dolls' Frontline",
        subTitle: "Girls' Frontline (2022)",
        thumbnail: "assets/images/img-film/top film/DOLLS' FRONTLINE.jpg",
        backgroundImg: 'https://i.pinimg.com/564x/60/c7/af/60c7af896ec257874789dbb6fc031e34.jpg',
        view: 57000,
        episode: '04/??',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: true,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["PdL-T2rwA", "8aNVMGIIRO", "YE96qlGDO", "W9pNgqIEUW"]
    },
    {
        filmName: 'Hồi Ký Vanitas',
        subTitle: 'Vanitas no Carte - The Case Study of Vanitas (2021)',
        thumbnail: 'assets/images/img-film/top film/HỒI KÍ VANITAS.jpg',
        backgroundImg: 'https://ecdn.game4v.com/g4v-content/uploads/2021/12/11080606/The-Case-Study-of-Vanitas-part-2-2-game4v-1639184762-96.png',
        view: 49000,
        episode: '15/24',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: true,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: []
    },
    {
        filmName: 'Karakai Jouzu No Takagi-San 3',
        subTitle: 'Karakai Jouzu no Takagi-san Third Season, Teasing Master Takagi-san(2022)',
        thumbnail: 'assets/images/img-film/top film/KARAKAI JOUZU NO TAKAGI-SAN 3.jpg',
        backgroundImg: 'https://wallpaperspeed.id/wp-content/uploads/2022/03/Karakai-Jouzu-no-Takagi-san-3-09-49.jpg',
        view: 52000,
        episode: '04/??',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: false,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["InPBuWq0c", "PJeF_FMc", "19HKLXnx6", "XfT4KnlQY"]
    },
    {
        filmName: 'Maiko-San Chi No Makanai-San',
        subTitle: 'The caterer at the Maiko Manor, Kiyo in Kyoto: From the Maiko House (2021)',
        thumbnail: 'assets/images/img-film/top film/MAIKO-SAN CHI NO MAKANAI-SAN.jpg',
        backgroundImg: 'https://i.ytimg.com/vi_webp/SZyuBw3dhOU/maxresdefault.webp',
        view: 14000,
        episode: '12/??',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: true,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: []
    },
    {
        filmName: 'Nghịch Thiên Chí Tôn',
        subTitle: 'Nghịch Thiên Chí Tôn (2021)',
        thumbnail: 'assets/images/img-film/top film/NGHỊCH THIÊN CHÍ TÔN.jpg',
        backgroundImg: "https://allimages.sgp1.digitaloceanspaces.com/tintapchicom/2021/08/Nghich-Thien-Chi-Ton-Tap-11-Vietsub-Thuyet-Minh.jpg",
        view: 98000,
        episode: '62/??',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: false,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["yUDFmuLe3", "jFzMq-INs", "w-HeuQkTJ", "ypP5G47WE", "mpn9Cls4e", "RYFaP-9_M"]
    },
    {
        filmName: 'Ousama Ranking',
        subTitle: 'King Ranking',
        thumbnail: 'assets/images/img-film/top film/OUSAMA RANKING.jpg',
        backgroundImg: 'https://cdn.wallpapersafari.com/70/65/km02En.png',
        view: 39000,
        episode: '15/23',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: true,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["-33BrvPZ2", "kY3cK1Cmm", "E2XVXs5vn", "IeVZqjho", "tehOa_ZWM", "Prjub2gHu", "hewiTmMqt", "wAXHOSPfm", "wVN7VN9bV"]
    },
    {
        filmName: 'Platinum End',
        subTitle: 'Platinum End (2021)',
        thumbnail: 'assets/images/img-film/top film/PLATINUM END.jpg',
        backgroundImg: 'https://images7.alphacoders.com/117/thumbbig-1172743.webp',
        view: 26000,
        episode: '16/24',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: false,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["Pnq_X-rbo", "Paq_X-rbO", "CHA80_zRe", "CHA80_zRe", "UPzimYESu", "UPzimYESu", "YQ5yu_dNq", "YQ5yu_dNq"]
    },
    {
        filmName: 'Saiyuuki Reload: Zeroin',
        subTitle: 'Saiyuuki Reload: Even a Worm Arc (2022)',
        thumbnail: 'assets/images/img-film/top film/SAIYUUKI RELOAD ZEROIN.jpg',
        backgroundImg: 'https://i0.wp.com/omnitos.com/wp-content/uploads/2022/01/Saiyuuki-Reload-Zeroin-Episode-3.jpg',
        view: 37000,
        episode: '04/??',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: true,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["J_vPPFTiM", "CB7UzvEru", "W_UEcZ-Ar", "6p7shwNwAy", "HLyj03PES", "1Z8qNZAUO", "tc2UoagHe", "xjKEJtpQe", "sRm3e-pCS6", "ojXVx6J_", "kzosIraDu", "RPjVSqyal", "wWk2rXGIQ"]
    },
    {
        filmName: 'Shingeki No Kyojin-The Final Season Part 2',
        subTitle: 'Shingeki no Kyojin Season 4, Attack on Titan Season 4 (2022)',
        thumbnail: 'assets/images/img-film/top film/SHINGEKI NO KYOJIN-THE FINAL SEASON PART 2.jpg',
        backgroundImg: 'https://animecorner.me/wp-content/uploads/2021/11/attack-on-titan-final-season-visual.png?ezimgfmt=ng%3Awebp%2Fngcb21%2Frs%3Adevice%2Frscb21-1',
        view: 90000,
        episode: '03/??',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: false,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["R4MVqnpPh", "QEeqrnFO0", "ivkvp6ZC_R", "kKCOFXbf_", "Wlc7v_GC9", "nfkBiYDZt", "svzR7d _hy", "X7UeKtugw", "YwrdoVGs0", "qr2UwUrbb", "qT33PmnHmX", "my3ErMI5F"]
    },
    {
        filmName: 'Slow Loop',
        subTitle: 'Slow Loop (2022)',
        thumbnail: 'assets/images/img-film/top film/SLOW LOOP.jpg',
        backgroundImg: 'https://images3.alphacoders.com/121/thumb-1920-1213192.jpg',
        view: 30000,
        episode: '04/??',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: true,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: []
    },
    {
        filmName: 'Thiếu Niên Ca Hành 2',
        subTitle: 'Thiếu Niên Ca Hành 2 (2021)',
        thumbnail: 'assets/images/img-film/top film/THIẾU NIÊN CA HÀNH 2.jpg',
        backgroundImg: 'https://ecdn.game4v.com/g4v-content/uploads/2021/06/gam4v-thieu-nien-ca-hanh.jpg',
        view: 96000,
        episode: '18/??',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: false,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: []
    },
    {
        filmName: 'Yêu Thần Ký',
        subTitle: 'Yêu Thần Ký (2017)',
        thumbnail: 'assets/images/img-film/top film/YÊU THẦN KÝ.jpg',
        backgroundImg: 'https://zingaudio.net/wp-content/uploads/2020/10/yeu-than-ky.jpg',
        view: 46000,
        episode: '201/???',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: true,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: []
    },
    {
        filmName: 'Đấu Phá Thương Khung OVA',
        subTitle: 'Đấu Phá Thương Khung OVA (2021)',
        thumbnail: 'assets/images/img-film/top film/ĐẤU PHÁ THƯƠNG KHUNG OVA.jpg',
        backgroundImg: 'https://ecdn.game4v.com/g4v-content/uploads/2021/07/game4v-11.jpg',
        view: 41000,
        episode: '13/13',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: true,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["uv-KUszRii", "qsISLasWz", "TDhWyQBu30", "jiYKSETKy", "tcoJzT5Ci", "qCrmw5nPo", "JnCDeHtBR", "vZqCX7Ezt", "ENTNdkFK5", "Ok43a44SN", "5F2FwEOz", "og-PBvYpG", "tOMPiLHh"]
    },
    {
        filmName: 'Ăn Không Uổng Kể Sơn Hải Kinh',
        subTitle: 'Ăn Không Uổng Kể Sơn Hải Kinh (2021)',
        thumbnail: 'assets/images/img-film/top film/ĂN KHÔNG UỔNG KỂ SƠN HẢI KINH.jpg',
        backgroundImg: 'https://pic.bstarstatic.com/ogv/07ec26b13704e80336a427abc3cdf3c3c5ad7471.png@960w_540h_1e_1c_1f.webp',
        view: 28000,
        episode: '16/??',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: true,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: []
    },
    {
        filmName: 'Đấu La Đại Lục',
        subTitle: 'Đấu La Đại Lục – Soul Land',
        thumbnail: 'assets/images/img-film/top film/dau-la-dai-luc-1-250x350.jpg.webp',
        backgroundImg: 'https://ss-images.saostar.vn/2020/02/24/7047527/1_fxmws8sjy0fo5ehbehzyia.png',
        view: 37000,
        episode: '193/???',
        urlVideo: '',
        desc: 'Đấu La Đại Lục là một trong những tác phẩm đặc sắc của Đường Gia Tam Thiếu. Tác phẩm thuộc thể loại Huyễn Hiệp, mang đến cho độc giả một cái nhìn, một cảm nhận mới về thế giới hiệp khách huyền ảo. Câu chuyện với nhân vật chính, con một thợ rèn, một thợ rèn trở thành tửu quỷ, vì thê tử đã mất, sẵn sàng lôi cuốn người đọc ngay từ những chương đầu tiên. Đấu La Thế Giới, một đại lục rộng lớn, cư dân đông đúc. Chức nghiệp cao quý nhất tại đây được gọi là Hồn Sư. Mỗi người sinh ra, đều có một vũ hồn bẩm sinh. Vũ hồn có thể là cái cày, cái cuốc, liêm đao… thuộc khối công cụ, một đóa hoa cúc, một cành mai… thuộc thực vật hệ, đến các vũ hồn cường đại như Tuyết Ảnh Ma Hùng, Tật Phong Ma Lang….',
        bookmark: true,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["EF6c22eqR", "6USJTAQ90"]
    },
    {
        filmName: 'Phàm Nhân Tu Tiên',
        subTitle: 'Phàm Nhân Tu Tiên - Phong Khởi Thiên Nam (2020)',
        thumbnail: 'assets/images/img-film/top film/Phàm Nhân Tu Tiên.jpg',
        backgroundImg: 'https://i.ytimg.com/vi/uZgyf0p9WXk/maxresdefault.jpg',
        view: 36000,
        episode: '34/??',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: true,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: []
    },
    {
        filmName: 'Vạn Giới Tiên Tung',
        subTitle: 'Vạn Giới Tiên Tung (2018)',
        thumbnail: 'assets/images/img-film/top film/Vạn Giới Tiên Tung.jpg',
        backgroundImg: 'https://static.fptplay.net/static/img/share/video/29_03_2018/van-gioi-tien-tung-229-03-2018_16g11-55.jpg',
        view: 37000,
        episode: '240/???',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: true,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: []
    },
    {
        filmName: 'Võ Thần Chúa Tể',
        subTitle: 'Võ Thần Chúa Tể (2020)',
        thumbnail: 'assets/images/img-film/top film/Võ Thần Chúa Tể.jpg',
        backgroundImg: 'https://s2.dmcdn.net/v/T92dV1X1XpL9avReN',
        view: 59000,
        episode: '200/???',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: true,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: []
    },
    {
        filmName: 'Tuyết Ưng Lĩnh Chủ Phần 3',
        subTitle: 'Tuyết Ưng Lĩnh Chủ Phần 3 (2021)',
        thumbnail: 'assets/images/img-film/top film/Tuyết Ưng Lĩnh Chủ Phần 3.jpg',
        backgroundImg: 'https://ecdn.game4v.com/g4v-content/uploads/2021/10/29151308/game4v-tuyet-ung-linh-chu-2-1635495188-92.jpg',
        view: 19000,
        episode: '06/??',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: false,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: []
    },
    {
        filmName: 'Thôn Phệ Tinh Không',
        subTitle: 'Swallowed Star (2020)',
        thumbnail: 'assets/images/img-film/top film/Thôn Phệ Tinh Không.jpg',
        backgroundImg: 'https://img.subhay.net/date/info/Swallowed-Star-Nga-Cat-Tay-Hong-Thi-2.jpg',
        view: 21000,
        episode: '32/??',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: true,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: []
    },
    {
        filmName: 'Koroshi Ai',
        subTitle: 'Love of Kill',
        thumbnail: 'assets/images/img-film/top film/Koroshi Ai.jpg',
        backgroundImg: 'https://www.playerone.vg/wp-content/uploads/2021/07/Koroshi-Ai-produccion.jpg',
        view: 8000,
        episode: '03/??',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: false,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: []
    },
    {
        filmName: 'Pocket Monsters: Kami To Yobareshi Arceus',
        subTitle: 'Pocket Monsters',
        thumbnail: 'assets/images/img-film/top film/Pocket Monsters Kami To Yobareshi Arceus.jpg',
        backgroundImg: 'https://media.voocdn.com/media/image/id/61f8d5ce0df93879589429ef_720x',
        view: 2000,
        episode: '02/04',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: false,
        type: 'Anime, Hành động, Shounen, Siêu nhiên, Viễn tưởng',
        slugs: []
    },
    {
        filmName: 'Kena No Deshi Wo Nanoru Kenja',
        subTitle: 'She Professed Herself Pupil of the Wise Man, Kendeshi',
        thumbnail: 'assets/images/img-film/top film/Kena No Deshi Wo Nanoru Kenja.jpg',
        backgroundImg: 'https://i.pinimg.com/originals/ab/a9/de/aba9de03361d8a7c5987c2d00eb65aa9.jpg',
        view: 19000,
        episode: '03/??',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: false,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: []
    },
    {
        filmName: 'Sabikui Bisco',
        subTitle: 'Rust-Eater Bisco',
        thumbnail: 'assets/images/img-film/top film/Sabikui Bisco.jpg',
        backgroundImg: 'https://images8.alphacoders.com/120/1204312.jpg',
        view: 10000,
        episode: '03/??',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: false,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: []
    },
    {
        filmName: 'Sabiiro No Armor: Reimei',
        subTitle: 'Rusted Armors',
        thumbnail: 'assets/images/img-film/top film/Sabiiro No Armor Reimei.jpg',
        backgroundImg: 'https://honeysanime.com/wp-content/uploads/2021/06/Sabiiro-no-Armor-Rusted-Armors-Magoichi-scaled.jpg',
        view: 2200,
        episode: '03/??',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: true,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: []
    },
    {
        filmName: 'Tabi Wa Ni',
        subTitle: 'Tabi Hani',
        thumbnail: 'assets/images/img-film/top film/Tabi Wa Ni.jpg',
        backgroundImg: 'https://gamenewsnetwork.net/wp-content/uploads/2021/12/1640271326_723_Doan-gioi-thieu-moi-da-ra-mat-Chi-tiet-phat.jpg',
        view: 283,
        episode: '05/??',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: false,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: []
    },
    {
        filmName: 'Leadale No DaiChi Nite',
        subTitle: 'World of Leadale, In the Land of Leadale',
        thumbnail: 'assets/images/img-film/top film/Leadale No DaiChi Nite.jpg',
        backgroundImg: 'https://static.zerochan.net/Leadale.no.Daichi.nite.full.3546796.jpg',
        view: 41000,
        episode: '04/??',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: false,
        type: 'Anime, Hành động, Shounen, Siêu nhiên, Viễn tưởng',
        slugs: []
    },
    {
        filmName: "Tokyo Revengers",
        subTitle: "Tokyo Revengers (2021)",
        thumbnail: "assets/images/img-film/film-category/Shounen/Tokyo Revengers.jpg",
        backgroundImg: 'https://images7.alphacoders.com/115/1155001.jpg',
        view: 881000,
        episode: '24/24',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: true,
        type: 'Anime, Hành động, Shounen, Viễn tưởng',
        slugs: []
    },
    {
        filmName: "Kimetsu No Yaiba: Mugen Ressha-hen",
        subTitle: "Kimetsu no Yaiba Movie: Mugen Ressha-hen (TV) (2021)",
        thumbnail: "assets/images/img-film/film-category/Shounen/Kimetsu No Yaiba Mugen Ressha-hen.jpg",
        backgroundImg: 'https://jpsharing.net/wp-content/uploads/2021/10/Kimetsu-no-yaiba-movie-jpsharing.net-2-1.jpg',
        view: 357000,
        episode: '07/07',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: true,
        type: 'Anime, Hành động, Shounen, Viễn tưởng',
        slugs: []
    },
    {
        filmName: "Tensei Shirata Slime Datta Ken 2ND Season",
        subTitle: "Vào Ngày Đó Tôi Đã Chuyển Sinh Thành Con Slime | That Time I Got Reincarnated as a Slime Season 2, Tensura 2 (2020)",
        thumbnail: "assets/images/img-film/film-category/Shounen/TENSEI SHITARA SLIME DATTA KEN 2ND SEASON.jpg",
        backgroundImg: 'https://gamek.mediacdn.vn/133514250583805952/2021/8/30/tensei-shitara-slime-datta-ken-1-752x440-16303290822591498423164.jpg',
        view: 2162000,
        episode: '24/24',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: true,
        type: 'Anime, Hành động, Shounen, Viễn tưởng, Chuyển sinh',
        slugs: []
    },
    {
        filmName: "Tensura Nikki Tensei Shirata Slime Datta Ken",
        subTitle: "The Slime Diaries: That Time I Got Reincarnated as a Slime (2021)",
        thumbnail: "assets/images/img-film/film-category/Shounen/TENSURA NIKKI TENSEI SHITARA SLIME DATTA KEN.jpg",
        backgroundImg: 'https://thuvienanime.com/wp-content/uploads/2021/09/Tensei-shitara-Slime-Datta-Ken.jpg',
        view: 751000,
        episode: '12/12',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: false,
        type: 'Anime, Hành động, Shounen, Viễn tưởng, Chuyển sinh',
        slugs: []
    },
    {
        filmName: "Edens Zero",
        subTitle: "Edens Zero (2021)",
        thumbnail: "assets/images/img-film/film-category/Shounen/Edens Zero.jpg",
        backgroundImg: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3UnAUZ19_gcGZSxNa9rZHKzxRD-nUy1kETbeSx11Pt4kiK_J3F972jy2y9hTbyMtGboQ&usqp=CAU',
        view: 751000,
        episode: '23/??',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: false,
        type: 'Anime, Hành động, Shounen, Viễn tưởng',
        slugs: []
    },
    {
        filmName: "Fumetsu No Anata E",
        subTitle: "Gửi em, người bất tử (2021)",
        thumbnail: "assets/images/img-film/film-category/Shounen/Fumetsu No Anata E.jpg",
        backgroundImg: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQloxU_8Q8A3MJdn2PPMt7M5ZVlGPFVSlL65wiTOhrpVSUwMPH17zh0BFXNep822IMBPgs&usqp=CAU',
        view: 650000,
        episode: '20/??',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: false,
        type: 'Anime, Hành động, Shounen, Viễn tưởng',
        slugs: []
    },
    {
        filmName: "Shaman King",
        subTitle: "Shaman King (2021) (2021)",
        thumbnail: "assets/images/img-film/film-category/Shounen/Shaman King.jpg",
        backgroundImg: 'https://i0.wp.com/anitrendz.net/news/wp-content/uploads/2021/06/Shaman-King-Soundtrack-scaled-e1624581333444.jpg',
        view: 595000,
        episode: '41/52',
        urlVideo: '',
        desc: '',
        bookmark: false,
        type: 'Anime, Hành động, Shounen, Viễn tưởng',
        slugs: []
    },
    {
        filmName: "Kakushigoto Movie",
        subTitle: "Hidden Things Movie (2021)",
        thumbnail: "assets/images/img-film/film-category/Shounen/Karushigoto Movie.jpg",
        backgroundImg: 'https://images5.alphacoders.com/107/1073869.jpg',
        view: 21000,
        episode: '01/01',
        urlVideo: '',
        desc: '',
        bookmark: true,
        type: 'Anime, Hành động, Shounen, Viễn tưởng',
        slugs: []
    },
    {
        filmName: "Boruto: Naruto Next Generations",
        subTitle: "BORUTO -NARUTO NEXT GENERATIONS- ( Naruto Season 3) | Boruto: Naruto những thế hệ kế tiếp (2017)",
        thumbnail: "assets/images/img-film/film-category/Shounen/BORUTO NARUTO NEXT GENERATIONS.jpg",
        backgroundImg: 'https://static.ssphim.net/static/5fe2d564b3fa6403ffa11d1c/60939d111563bd83d552ae11_boruto-1.jpg',
        view: 4966000,
        episode: '234/???',
        urlVideo: '',
        desc: '',
        bookmark: true,
        type: 'Anime, Hành động, Shounen, Viễn tưởng',
        slugs: []
    },
    {
        filmName: "Nanatsu No Taizai Movie 2 Hikari Ni Norowareshi Mono-Tachi",
        subTitle: "Gekijouban Nanatsu no Taizai Hikari ni Norowareshi Mono-tachi, The Seven Deadly Sins the Movie: Cursed by Light (2021)",
        thumbnail: "assets/images/img-film/film-category/Shounen/NANATSU NO TAIZAI MOVIE 2 HIKARI NI NOROWARESHI MONO-TACHI.jpg",
        backgroundImg: 'https://i3.wp.com/img.bilutv.cc/film/18637/big.jpg',
        view: 80000,
        episode: '01/01',
        urlVideo: '',
        desc: '',
        bookmark: true,
        type: 'Anime, Hành động, Shounen, Viễn tưởng',
        slugs: []
    },
    {
        filmName: "Vua Hải Tặc",
        subTitle: "One Piece | Đảo Hải Tặc (1999)",
        thumbnail: "assets/images/img-film/film-category/Shounen/Vua Hải Tặc.jpg",
        backgroundImg: 'https://i.pinimg.com/originals/a2/84/29/a284294e7badfbda66fea132db44dc76.jpg',
        view: 5212000,
        episode: '1008/????',
        urlVideo: '',
        desc: '',
        bookmark: false,
        type: 'Anime, Hành động, Shounen, Viễn tưởng',
        slugs: []
    },
    {
        filmName: "Dragon Ball Heroes",
        subTitle: "Dragon Ball Heroes (2018)",
        thumbnail: "assets/images/img-film/film-category/Shounen/Dragon Ball Heroes.jpg",
        backgroundImg: 'https://i.pinimg.com/originals/b8/09/20/b80920500b773a22ec8af4af240c1340.jpg',
        view: 897000,
        episode: '23/??',
        urlVideo: '',
        desc: '',
        bookmark: true,
        type: 'Anime, Hành động, Shounen, Viễn tưởng',
        slugs: []
    },
];

export const topView = [
    {
        filmName: "Kimetsu No Yaiba ss2: Yuukaku-hen",
        subTitle: "Kimetsu No Yaiba ss2: Yuukaku-hen",
        view: 97000,
        top1: true,
        desc: "Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ",
        bookmark: true,
        episode: "08/??",
        thumbnail: "assets/images/kimetsu-no-yaiba-ss2-thanh-guom-diet-quy-phan-2-1-250x350.jpg.webp",
        backgroundImg: "https://file.hstatic.net/1000231532/file/r_kimetsu_no_yaiba_-_the_hinokami_chronicles_ra_mat_trailer_cot_truyen_d82208c8197542a9a9db3506b45bc944.jpg",
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: []
    },
    {
        filmName: "Black Clover",
        subTitle: "Thế Giới Phép Thuật",
        view: 67000,
        top1: false,
        desc: "Anime Black Clover - Thế Giới Phép Thuật là 1 bộ phim thuộc thể loại phép thuật, phiêu lưu vô cùng nổi tiếng. Phim Black Clover là câu chuyện về 2 chàng trai Asta và Yuno, họ đã bị bỏ rơi cùng nhau tại cùng một nhà thờ và đã không thể tách rời kể từ đó. Khi còn trẻ, họ hứa sẽ cạnh tranh với nhau để xem ai sẽ trở thành Ma Pháp Đế tiếp theo.",
        bookmark: true,
        episode: "153/???",
        thumbnail: "https://i.pinimg.com/originals/0a/2a/e8/0a2ae87158dbd761d30dd7be5517cfff.jpg",
        backgroundImg: "https://images3.alphacoders.com/911/911611.png",
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: []
    },
    {
        filmName: "Đấu La Đại Lục",
        subTitle: "Douluo Dalu, Combat Continent, Soul Land",
        view: 43000,
        top1: false,
        desc: "Đấu La Đại Lục là một trong những tác phẩm đặc sắc của Đường Gia Tam Thiếu. Tác phẩm thuộc thể loại Huyễn Hiệp, mang đến cho độc giả một cái nhìn, một cảm nhận mới về thế giới hiệp khách huyền ảo. Câu chuyện với nhân vật chính, con một thợ rèn, một thợ rèn trở thành tửu quỷ, vì thê tử đã mất, sẵn sàng lôi cuốn người đọc ngay từ những chương đầu tiên. Đấu La Thế Giới, một đại lục rộng lớn, cư dân đông đúc. Chức nghiệp cao quý nhất tại đây được gọi là Hồn Sư. Mỗi người sinh ra, đều có một vũ hồn bẩm sinh. Vũ hồn có thể là cái cày, cái cuốc, liêm đao… thuộc khối công cụ, một đóa hoa cúc, một cành mai… thuộc thực vật hệ, đến các vũ hồn cường đại như Tuyết Ảnh Ma Hùng, Tật Phong Ma Lang…. ",
        bookmark: true,
        episode: "215/???",
        thumbnail: "assets/images/img-film/top-view-film/dau-la-dai-luc-1-250x350.jpg.webp",
        backgroundImg: "https://ss-images.saostar.vn/2020/02/24/7047527/1_fxmws8sjy0fo5ehbehzyia.png",
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["EF6c22eqR", "6USJTAQ90"]
    },
    {
        filmName: "Doraemon New TV Series",
        subTitle: "Doremon | Chú Mèo máy thần kỳ | Mèo Máy Doraemon | Đôrêmon",
        view: 38000,
        top1: false,
        desc: "Các câu chuyện trong Doraemon thường có một công thức chung, đó là xoay quanh những rắc rối hay xảy ra với cậu bé Nobita học lớp bốn, nhân vật chính thứ nhì của bộ truyện. Doraemon có một chiếc túi thần kỳ trước bụng với đủ loại bảo bối của tương lai. Cốt truyện thường gặp nhất sẽ là Nobita trở về nhà khóc lóc với những rắc rối mà cậu gặp phải ở trường hoặc với bạn bè. Sau khi bị cậu bé van nài hoặc thúc giục, Doraemon sẽ đưa ra một bảo bối giúp Nobita giải quyết những rắc rối của mình, hoặc là để trả đũa hay khoe khoang với bạn bè của cậu. Nobita sẽ lại thường đi quá xa so với dự định ban đầu của Doraemon, thậm chí với những bảo bối mới cậu còn gặp rắc rối lớn hơn trước đó. Đôi khi những người bạn của Nobita, thường là Suneo (Xêkô) hoặc Jaian (Chaien) lại lấy trộm những bảo bối và sử dụng chúng không đúng mục đích. Tuy nhiên thường thì ở cuối mỗi câu chuyện, những ai sử dụng sai mục đích bảo bối sẽ phải chịu hậu quả do mình gây ra, và người đọc sẽ rút ra được bài học từ đó.",
        bookmark: true,
        episode: "713/???",
        thumbnail: "assets/images/img-film/top-view-film/doraemon-new-tv-series.jpg",
        backgroundImg: "https://cdn.voh.com.vn/voh/thumbnail/2022/03/12/list-15-phim-hoat-hinh-doraemon-tap-dai.jpg",
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: []
    },
    {
        filmName: "Arifureta Shokugyou de Sekai Saikyou 2nd Season",
        subTitle: "From Common Job Class to the Strongest in the World 2nd Season",
        view: 34000,
        top1: false,
        desc: "Mùa hai của Arifureta Shokugyou de Sekai Saikyou.",
        bookmark: true,
        episode: "12/12",
        thumbnail: "assets/images/img-film/top-view-film/arifureta-shokugyou-de-sekai-saikyou-2nd-season.jpg",
        backgroundImg: "https://www.kaorinusantara.or.id/wp-content/uploads/2019/10/arifureta.jpg",
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: []
    },
    {
        filmName: "Naruto: Shippuuden",
        subTitle: "Naruto Hurricane Chronicles, Naruto: Sức Mạnh Vĩ Thú | Naruto Phần",
        view: 32000,
        top1: false,
        desc: "Naruto Shippuden hay còn được gọi với cái tên quen thuộc Naruto phần 2 là phần tiếp theo của bộ phim hoạt hình nổi tiếng Naruto, lấy bối cảnh hai năm rưỡi sau khi Naruto rời làng Lá. Naruto Shippuden tiếp tục theo chân chàng ninja trẻ tuổi Naruto Uzumaki trong cuộc hành trình luyện tập cực khổ để trở thành ninja giỏi nhất. Trong khi đó, Akatsuki, một tổ chức bí ẩn tập hợp những ninja phản diện tài giỏi bậc nhất, đang từng bước thực hiện kế hoạch lớn của chúng, đe dọa sự an toàn của thế giới ninja. Naruto sẽ làm gì để bảo vệ làng Lá và những người mà cậu yêu quý?",
        bookmark: true,
        episode: "500/???",
        thumbnail: "assets/images/img-film/top-view-film/naruto-shippuuden-thumbnail.jpg",
        backgroundImg: "https://cdn.tgdd.vn/2020/07/content/thumb-800x450-33.jpg",
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: []
    },
    {
        filmName: "Ousama Ranking",
        subTitle: "King Ranking, Bảng Xếp Hạng Quốc Vương",
        view: 32000,
        top1: false,
        desc: 'Phim xoay quanh Bojji, một hoàng tử bị điếc, bất lực, thậm chí không thể sử dụng thanh kiếm của trẻ em. Là con trai đầu lòng, anh phấn đấu hết mình và ước mơ trở thành vị vua vĩ đại nhất thế giới. Tuy nhiên, mọi người đồn thổi về anh sau lưng anh là "một hoàng tử chẳng ra gì" và "không thể nào anh có thể làm vua được." Bojji có thể kết bạn đầu tiên của mình, "Kage" (bóng tối) —một cái bóng theo nghĩa đen trên mặt đất, người bằng cách nào đó hiểu rõ Bojji. (Kage là một người sống sót trong gia tộc sát thủ Kage đã bị xóa sổ. Không còn là một kẻ giết người, Kage giờ đây kiếm sống bằng cách ăn trộm.) với cuộc gặp gỡ định mệnh của mình với Kage.',
        bookmark: true,
        episode: "15/23",
        thumbnail: "assets/images/img-film/top-view-film/bang-xep-hang-quoc-vuong-ousama-ranking-thumbnail.jpg",
        backgroundImg: "https://cdn.wallpapersafari.com/70/65/km02En.png",
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["-33BrvPZ2", "kY3cK1Cmm", "E2XVXs5vn", "IeVZqjho", "tehOa_ZWM", "Prjub2gHu", "hewiTmMqt", "wAXHOSPfm", "wVN7VN9bV"]
    },
    {
        filmName: "Shikkakumon no Saikyou Kenja",
        subTitle: "The Strongest Sage of Disqualified Crest, Shikkakumon no Saikyokenja",
        view: 30000,
        top1: false,
        desc: "Sức mạnh của anh ta bị giới hạn bởi huy hiệu ma thuật mà anh ta có từ khi được sinh ra, Mathias, nhà hiền triết mạnh nhất thế giới, quyết định phải chuyển sinh để trở thành người mạnh nhất. Khi tái sinh là một cậu bé, Mathias rất vui mừng khi phát hiện ra rằng cậu được sinh ra với huy hiệu tối ưu để chiến đấu bằng phép thuật trong lần thử đầu tiên! Thật không may, thế giới mà anh ấy sinh ra có những tiêu chuẩn cực kỳ kém về phép thuật, và mọi người đều nghĩ rằng anh ấy vẫn là kẻ thất bại! Bây giờ Mathias phải chứng minh mọi người sai… theo phong cách của nhà hiền triết mạnh nhất thế giới!",
        bookmark: false,
        episode: "12/12",
        thumbnail: "assets/images/img-film/top-view-film/shikkakumon-no-saikyou-kenja-thumbnail.jpg",
        backgroundImg: "https://truyengihot.net/uploads/anime/cover_1641666501.jpg",
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: []
    },
    {
        filmName: "Sono Bisque Doll wa Koi wo Suru",
        subTitle: "My Dress-Up Darling, Sono Kisekae Ningyou wa Koi wo Suru",
        view: 29000,
        top1: false,
        desc: "Wakana Gojou là một thằng giai tân mười lăm tuổi, người bị sang chấn tâm lí trong quá khứ do niềm đam mê của mình. Sự cố đó đã để lại dấu ấn cho anh khiến anh trở thành một người ẩn dật xã hội. Cho đến một ngày, anh đã gặp phải Kitagawa, một gyaru hòa đồng, hoàn toàn trái ngược với anh. Họ sớm chia sẻ niềm đam mê của họ với nhau mà dẫn đến mối quan hệ kỳ quặc của họ.",
        bookmark: true,
        episode: "12/12",
        thumbnail: "assets/images/img-film/top-view-film/sono-bisque-doll-wa-koi-wo-suru-thumbnail.jpg",
        backgroundImg: "https://static.lag.vn/upload/news/21/12/06/anime-Sono-Bisque-Doll-Wa-Koi-Wo-Suru_DGYY.jpg?w=800&encoder=wic&subsampling=444",
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: []
    },
    {
        filmName: "King's Raid: Ishi Wo Tsugumono-Tachi",
        subTitle: "Kings Raid: Ishi wo Tsugumono-tachi (2020)",
        view: 26000,
        top1: false,
        desc: "Đã 100 năm kể từ khi vua Kyle chôn cất Ang Mundo. Bây giờ trong thời kỳ hòa bình, hiệp sĩ tập sự Kasel tận hưởng cuộc sống của mình mà không cần lo lắng. Tuy nhiên, số phận của anh ta bắt đầu thay đổi, với tin tức về những con quỷ xuất hiện xâm chiếm khu phố. Được hướng dẫn bởi một người đàn ông thông thái, Kasel tìm thấy những người bạn mà anh có thể dựa vào và bắt đầu sứ mệnh tìm kiếm thánh kiếm, có khả năng tiêu diệt kẻ thù mới tìm thấy của mình.",
        bookmark: false,
        episode: "26/26",
        thumbnail: "assets/images/img-film/top-view-film/King raid.jpg",
        backgroundImg: "https://i.ytimg.com/vi/7FyrUKmai3I/maxresdefault.jpg",
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: []
    },
]

export const topComment = [
    {
        filmName: "Black Clover",
        subTitle: "Thế Giới Phép Thuật",
        comment: 980,
        top1: true,
        desc: "Anime Black Clover - Thế Giới Phép Thuật là 1 bộ phim thuộc thể loại phép thuật, phiêu lưu vô cùng nổi tiếng. Phim Black Clover là câu chuyện về 2 chàng trai Asta và Yuno, họ đã bị bỏ rơi cùng nhau tại cùng một nhà thờ và đã không thể tách rời kể từ đó. Khi còn trẻ, họ hứa sẽ cạnh tranh với nhau để xem ai sẽ trở thành Ma Pháp Đế tiếp theo.",
        bookmark: true,
        episode: "153/???",
        thumbnail: "https://i.pinimg.com/originals/0a/2a/e8/0a2ae87158dbd761d30dd7be5517cfff.jpg",
        backgroundImg: "https://images3.alphacoders.com/911/911611.png",
        type: 'Phiêu lưu',
        slugs: []
    },
    {
        filmName: "Jujutsu Kaisen",
        subTitle: "Sorcery Fight (2020)",
        comment: 920,
        top1: false,
        desc: "Thiếu niên Itadori Yuuji, mang năng lực thể chất phi thường, trải qua cuộc sống học sinh cấp 3 bình thường, nhưng đến một ngày vì cứu bạn bè bị đe doạ bởi “lời nguyền”, cậu đã nuốt chú vật đặc cấp - “Ngón tay của Ryomen Sukuna” và để cho lời nguyền trú ngụ trong linh hồn mình.",
        bookmark: true,
        episode: "10/24",
        thumbnail: "assets/images/img-film/top-film-cmt/Jujutsu Kaisen.jpg",
        backgroundImg: "https://i0.wp.com/dmtalkies.com/wp-content/uploads/2021/08/ezgif-1-078409066a3b-compressed-1.jpg?fit=1200%2C674&ssl=1",
        type: 'Hành động, viễn tưởng',
        slugs: []
    },
    {
        filmName: "Arifureta Shokugyou De Sekai Saikyou 2nd Season",
        subTitle: "From Common Job Class to the Strongest in the World 2nd Season",
        comment: 900,
        top1: false,
        desc: "Mùa hai của Arifureta Shokugyou de Sekai Saikyou.",
        bookmark: true,
        episode: "12/12",
        thumbnail: "assets/images/img-film/top-film-cmt/arifureta-shokugyou-de-sekai-saikyou-2nd-season.jpg",
        backgroundImg: "https://www.kaorinusantara.or.id/wp-content/uploads/2019/10/arifureta.jpg",
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: []
    },
    {
        filmName: "Ousama Ranking",
        subTitle: "King Ranking, Bảng Xếp Hạng Quốc Vương",
        comment: 500,
        top1: false,
        desc: 'Phim xoay quanh Bojji, một hoàng tử bị điếc, bất lực, thậm chí không thể sử dụng thanh kiếm của trẻ em. Là con trai đầu lòng, anh phấn đấu hết mình và ước mơ trở thành vị vua vĩ đại nhất thế giới. Tuy nhiên, mọi người đồn thổi về anh sau lưng anh là "một hoàng tử chẳng ra gì" và "không thể nào anh có thể làm vua được." Bojji có thể kết bạn đầu tiên của mình, "Kage" (bóng tối) —một cái bóng theo nghĩa đen trên mặt đất, người bằng cách nào đó hiểu rõ Bojji. (Kage là một người sống sót trong gia tộc sát thủ Kage đã bị xóa sổ. Không còn là một kẻ giết người, Kage giờ đây kiếm sống bằng cách ăn trộm.) với cuộc gặp gỡ định mệnh của mình với Kage.',
        bookmark: true,
        episode: "15/23",
        thumbnail: "assets/images/img-film/top-film-cmt/bang-xep-hang-quoc-vuong-ousama-ranking-thumbnail.jpg",
        backgroundImg: "https://cdn.wallpapersafari.com/70/65/km02En.png",
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["-33BrvPZ2", "kY3cK1Cmm", "E2XVXs5vn", "IeVZqjho", "tehOa_ZWM", "Prjub2gHu", "hewiTmMqt", "wAXHOSPfm", "wVN7VN9bV"]
    },
    {
        filmName: "Majo No Tabitabi",
        subTitle: "The Journey of Elaina | Wandering Witch: The Journey of Elaina (2020)",
        comment: 480,
        top1: false,
        desc: "Ngày xửa ngày xưa, xưa ơi là xưa, xưa thiệt là xưa, có một cô phù thủy tên là Elaina, cô chính là người sẽ có cuộc hành trình đi xuyên thế giới. Trên đường đi, cô sẽ gặp rất nhiều người, nhiều nơi. Từ một vùng đất đầy phù thủy đến một nơi có những tên khổng lồ cuồng cơ bắp nhưng trong mỗi cuộc gặp gỡ, Elaina sẽ bắt tay trở thành một phần nhỏ trong câu chuyện của họ và về thế giới riêng của cô nàng bé nhỏ này.",
        bookmark: false,
        episode: "12/12",
        thumbnail: "assets/images/img-film/top-film-cmt/Majo No Tabitabi.jpg",
        backgroundImg: "https://i.ytimg.com/vi/SpTgCQGWqqc/maxresdefault.jpg",
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: []
    },
    {
        filmName: "Doraemon New Tv Series",
        subTitle: "Doremon | Chú Mèo máy thần kỳ | Mèo Máy Doraemon | Đôrêmon",
        comment: 200,
        top1: false,
        desc: "Các câu chuyện trong Doraemon thường có một công thức chung, đó là xoay quanh những rắc rối hay xảy ra với cậu bé Nobita học lớp bốn, nhân vật chính thứ nhì của bộ truyện. Doraemon có một chiếc túi thần kỳ trước bụng với đủ loại bảo bối của tương lai. Cốt truyện thường gặp nhất sẽ là Nobita trở về nhà khóc lóc với những rắc rối mà cậu gặp phải ở trường hoặc với bạn bè. Sau khi bị cậu bé van nài hoặc thúc giục, Doraemon sẽ đưa ra một bảo bối giúp Nobita giải quyết những rắc rối của mình, hoặc là để trả đũa hay khoe khoang với bạn bè của cậu. Nobita sẽ lại thường đi quá xa so với dự định ban đầu của Doraemon, thậm chí với những bảo bối mới cậu còn gặp rắc rối lớn hơn trước đó. Đôi khi những người bạn của Nobita, thường là Suneo (Xêkô) hoặc Jaian (Chaien) lại lấy trộm những bảo bối và sử dụng chúng không đúng mục đích. Tuy nhiên thường thì ở cuối mỗi câu chuyện, những ai sử dụng sai mục đích bảo bối sẽ phải chịu hậu quả do mình gây ra, và người đọc sẽ rút ra được bài học từ đó.",
        bookmark: true,
        episode: "713/???",
        thumbnail: "assets/images/img-film/top-film-cmt/doraemon-new-tv-series.jpg",
        backgroundImg: "https://cdn.voh.com.vn/voh/thumbnail/2022/03/12/list-15-phim-hoat-hinh-doraemon-tap-dai.jpg",
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: []
    },
    {
        filmName: "Đấu La Đại Lục",
        subTitle: "Douluo Dalu, Combat Continent, Soul Land",
        comment: 190,
        top1: false,
        desc: "Đấu La Đại Lục là một trong những tác phẩm đặc sắc của Đường Gia Tam Thiếu. Tác phẩm thuộc thể loại Huyễn Hiệp, mang đến cho độc giả một cái nhìn, một cảm nhận mới về thế giới hiệp khách huyền ảo. Câu chuyện với nhân vật chính, con một thợ rèn, một thợ rèn trở thành tửu quỷ, vì thê tử đã mất, sẵn sàng lôi cuốn người đọc ngay từ những chương đầu tiên. Đấu La Thế Giới, một đại lục rộng lớn, cư dân đông đúc. Chức nghiệp cao quý nhất tại đây được gọi là Hồn Sư. Mỗi người sinh ra, đều có một vũ hồn bẩm sinh. Vũ hồn có thể là cái cày, cái cuốc, liêm đao… thuộc khối công cụ, một đóa hoa cúc, một cành mai… thuộc thực vật hệ, đến các vũ hồn cường đại như Tuyết Ảnh Ma Hùng, Tật Phong Ma Lang….",
        bookmark: true,
        episode: "215/???",
        thumbnail: "assets/images/img-film/top-film-cmt/dau-la-dai-luc-1-250x350.jpg.webp",
        backgroundImg: "https://ss-images.saostar.vn/2020/02/24/7047527/1_fxmws8sjy0fo5ehbehzyia.png",
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["EF6c22eqR", "6USJTAQ90"]
    },
    {
        filmName: "Adachi To Shimamura",
        subTitle: "Adachi and Shimamura (2020)",
        comment: 100,
        top1: false,
        desc: "Tầng hai của phòng tập thể dục ― đây là nơi chúng tôi luôn gặp nhau. Đó là giờ học, nhưng tất nhiên, không có bất kỳ lớp học nào diễn ra ở một nơi như thế này.Đây là nơi tôi và Shimamura trở thành bạn của nhau. Chúng tôi đã đi chơi ở đây ― nói về các chương trình truyền hình và nấu ăn, chơi bóng bàn ... Đây là nơi chúng tôi nuôi dưỡng tình bạn của mình.Cúi đầu vào tường, tôi khẽ thở dài.Cảm giác này là gì? Hôm qua, tôi đã mơ thấy tôi và Shimamura hôn nhau.Không phải tôi như vậy. Tôi chắc rằng Shimamura cũng không.",
        bookmark: false,
        episode: " 12/12",
        thumbnail: "assets/images/img-film/top-film-cmt/Adachi To Shimamura.jpg",
        backgroundImg: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTyBFak6Vy0vpaUiBn-S6qEl7APLmgu7JND_w&usqp=CAU",
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: []
    },
    {
        filmName: "King's Raid: Ishi Wo Tsugumono-Tachi",
        subTitle: "Kings Raid: Ishi wo Tsugumono-tachi (2020)",
        comment: 86,
        top1: false,
        desc: "Đã 100 năm kể từ khi vua Kyle chôn cất Ang Mundo. Bây giờ trong thời kỳ hòa bình, hiệp sĩ tập sự Kasel tận hưởng cuộc sống của mình mà không cần lo lắng. Tuy nhiên, số phận của anh ta bắt đầu thay đổi, với tin tức về những con quỷ xuất hiện xâm chiếm khu phố. Được hướng dẫn bởi một người đàn ông thông thái, Kasel tìm thấy những người bạn mà anh có thể dựa vào và bắt đầu sứ mệnh tìm kiếm thánh kiếm, có khả năng tiêu diệt kẻ thù mới tìm thấy của mình.",
        bookmark: false,
        episode: "26/26",
        thumbnail: "assets/images/img-film/top-film-cmt/King raid.jpg",
        backgroundImg: "https://i.ytimg.com/vi/7FyrUKmai3I/maxresdefault.jpg",
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: []
    },
]

export const filmsTrend = [
    {
        filmName: 'Thanh Gươm Diệt Quỷ',
        subTitle: 'Kimetsu No Yaiba ss2: Yuukaku-hen',
        thumbnail: 'assets/images/kimetsu-no-yaiba-ss2-thanh-guom-diet-quy-phan-2-1-250x350.jpg.webp',
        backgroundImg: 'https://file.hstatic.net/1000231532/file/r_kimetsu_no_yaiba_-_the_hinokami_chronicles_ra_mat_trailer_cot_truyen_d82208c8197542a9a9db3506b45bc944.jpg',
        view: 97000,
        episode: '11/??',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: true,
        type: 'Anime, Hành động, Shounen, Siêu nhiên, Viễn tưởng',
        slugs: ["jDfmDW5B6", "K6P662qca", "51EQG9rrQ", "R6cILrKvv", "RZQFH5XOp", "bMHw5OjbH", "hJ2nIbs02", "hIouytgpG", "VDsN9VHBih", "9aCu_vUxJ", "z5GeOXnom"]
    },
    {
        filmName: 'Độc Bộ Tiêu Dao',
        subTitle: 'Độc Bộ Tiêu Dao (2020)',
        thumbnail: 'assets/images/img-film/top film/ĐỘC BỘ TIÊU DAO.jpg',
        backgroundImg: 'https://i.ytimg.com/vi/CgUf-l6cwik/maxresdefault.jpg',
        view: 43000,
        episode: '177/???',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: true,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["Y6zUF_KgQ", "15HN_zEJw", "-8D6qWg-V4", "JtKr2rlvo", "qh5sC8Bh2", "h-vJ96DpJ", "hf8X9CZ0p", "sMs38nkgGx", "971K77KLb", "7keTwhPbs", "2TP4bwCiO", "XVQIPKQie", "20mVrbElh", "dCZSoNcQa", "9dK7_XRjx", "uC_FjEeMx2", "vncx084pL", "FFnQOovble", "uELSuMvxk", "_89TG110P"]
    },
    {
        filmName: 'Nghịch Thiên Chí Tôn',
        subTitle: 'Nghịch Thiên Chí Tôn (2021)',
        thumbnail: 'assets/images/img-film/top film/NGHỊCH THIÊN CHÍ TÔN.jpg',
        backgroundImg: "https://allimages.sgp1.digitaloceanspaces.com/tintapchicom/2021/08/Nghich-Thien-Chi-Ton-Tap-11-Vietsub-Thuyet-Minh.jpg",
        view: 98000,
        episode: '62/??',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: false,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["yUDFmuLe3", "jFzMq-INs", "w-HeuQkTJ", "ypP5G47WE", "mpn9Cls4e", "RYFaP-9_M"]
    },
    {
        filmName: 'Ousama Ranking',
        subTitle: 'King Ranking',
        thumbnail: 'assets/images/img-film/top film/OUSAMA RANKING.jpg',
        backgroundImg: 'https://cdn.wallpapersafari.com/70/65/km02En.png',
        view: 39000,
        episode: '15/23',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: true,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["-33BrvPZ2", "kY3cK1Cmm", "E2XVXs5vn", "IeVZqjho", "tehOa_ZWM", "Prjub2gHu", "hewiTmMqt", "wAXHOSPfm", "wVN7VN9bV"]
    },
    {
        filmName: 'Kena No Deshi Wo Nanoru Kenja',
        subTitle: 'She Professed Herself Pupil of the Wise Man, Kendeshi',
        thumbnail: 'assets/images/img-film/top film/Kena No Deshi Wo Nanoru Kenja.jpg',
        backgroundImg: 'https://i.pinimg.com/originals/ab/a9/de/aba9de03361d8a7c5987c2d00eb65aa9.jpg',
        view: 19000,
        episode: '03/??',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: false,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: []
    },
    {
        filmName: 'Sabikui Bisco',
        subTitle: 'Rust-Eater Bisco',
        thumbnail: 'assets/images/img-film/top film/Sabikui Bisco.jpg',
        backgroundImg: 'https://images8.alphacoders.com/120/1204312.jpg',
        view: 10000,
        episode: '03/??',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: false,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: []
    },
    {
        filmName: 'Sabiiro No Armor: Reimei',
        subTitle: 'Rusted Armors',
        thumbnail: 'assets/images/img-film/top film/Sabiiro No Armor Reimei.jpg',
        backgroundImg: 'https://honeysanime.com/wp-content/uploads/2021/06/Sabiiro-no-Armor-Rusted-Armors-Magoichi-scaled.jpg',
        view: 2200,
        episode: '03/??',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: true,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: []
    },
    {
        filmName: 'Tabi Wa Ni',
        subTitle: 'Tabi Hani',
        thumbnail: 'assets/images/img-film/top film/Tabi Wa Ni.jpg',
        backgroundImg: 'https://gamenewsnetwork.net/wp-content/uploads/2021/12/1640271326_723_Doan-gioi-thieu-moi-da-ra-mat-Chi-tiet-phat.jpg',
        view: 283,
        episode: '05/??',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: false,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: []
    }
];

export const showTimes = [
    {
        filmName: 'Chân Võ Đỉnh Phong',
        subTitle: 'Chân Võ Đỉnh Phong (2021)',
        thumbnail: 'assets/images/img-film/top film/CHÂN VÕ ĐỈNH PHONG.jpg',
        backgroundImg: 'https://media.voocdn.com/media/image/id/61d5a6610df938bc4232bd0e_720x',
        view: 35000,
        episode: '12/??',
        date: 'monday',
        newEpisode: 13,
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: true,
        type: 'Anime, Hành động, Shounen, Siêu nhiên, Viễn tưởng',
        slugs: ["nmqgb9wsS0", "INwUdi7Hq", "oFylRKxeX", "9LATpI30C", "DiMCpjqkJ", "UzGQ4XoKM", "BmTcxGSGT", "KQIRq7ciy", "YhDWlc-cs", "mOtOpMNht", "WIanHTrfy", "cWe2H81sx", "m7WGESPlv"]
    },
    {
        filmName: "Dolls' Frontline",
        subTitle: "Girls' Frontline (2022)",
        thumbnail: "assets/images/img-film/top film/DOLLS' FRONTLINE.jpg",
        backgroundImg: 'https://i.pinimg.com/564x/60/c7/af/60c7af896ec257874789dbb6fc031e34.jpg',
        view: 57000,
        episode: '03/??',
        date: 'monday',
        newEpisode: 4,
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: false,
        type: 'Anime, Hành động, Shounen, Siêu nhiên, Viễn tưởng',
        slugs: ["PdL-T2rwA", "8aNVMGIIRO", "YE96qlGDO", "W9pNgqIEUW"]
    },
    {
        filmName: 'Platinum End',
        subTitle: 'Platinum End (2021)',
        thumbnail: 'assets/images/img-film/top film/PLATINUM END.jpg',
        backgroundImg: 'https://images7.alphacoders.com/117/thumbbig-1172743.webp',
        view: 26000,
        episode: '15/24',
        date: 'monday',
        newEpisode: 16,
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: true,
        type: 'Anime, Hành động, Shounen, Siêu nhiên, Viễn tưởng',
        slugs: ["Pnq_X-rbo", "Paq_X-rbO", "CHA80_zRe", "CHA80_zRe", "UPzimYESu", "UPzimYESu", "YQ5yu_dNq", "YQ5yu_dNq"]
    },
    {
        filmName: 'Thanh Gươm Diệt Quỷ',
        subTitle: 'Kimetsu No Yaiba ss2: Yuukaku-hen',
        thumbnail: 'assets/images/kimetsu-no-yaiba-ss2-thanh-guom-diet-quy-phan-2-1-250x350.jpg.webp',
        backgroundImg: 'https://file.hstatic.net/1000231532/file/r_kimetsu_no_yaiba_-_the_hinokami_chronicles_ra_mat_trailer_cot_truyen_d82208c8197542a9a9db3506b45bc944.jpg',
        view: 97000,
        episode: '11/??',
        date: 'tuesday',
        newEpisode: 10,
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: true,
        type: 'Anime, Hành động, Shounen, Siêu nhiên, Viễn tưởng',
        slugs: ["jDfmDW5B6", "K6P662qca", "51EQG9rrQ", "R6cILrKvv", "RZQFH5XOp", "bMHw5OjbH", "hJ2nIbs02", "hIouytgpG", "VDsN9VHBih", "9aCu_vUxJ", "z5GeOXnom"]
    },
    {
        filmName: 'Độc Bộ Tiêu Dao',
        subTitle: 'Độc Bộ Tiêu Dao (2020)',
        thumbnail: 'assets/images/img-film/top film/ĐỘC BỘ TIÊU DAO.jpg',
        backgroundImg: 'https://i.ytimg.com/vi/CgUf-l6cwik/maxresdefault.jpg',
        view: 43000,
        episode: '117/??',
        date: 'tuesday',
        newEpisode: 118,
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: true,
        type: 'Anime, Hành động, Shounen, Siêu nhiên, Viễn tưởng',
        slugs: ["Y6zUF_KgQ", "15HN_zEJw", "-8D6qWg-V4", "JtKr2rlvo", "qh5sC8Bh2", "h-vJ96DpJ", "hf8X9CZ0p", "sMs38nkgGx", "971K77KLb", "7keTwhPbs", "2TP4bwCiO", "XVQIPKQie", "20mVrbElh", "dCZSoNcQa", "9dK7_XRjx", "uC_FjEeMx2", "vncx084pL", "FFnQOovble", "uELSuMvxk", "_89TG110P"]
    },
    {
        filmName: 'Hồi Ký Vanitas',
        subTitle: 'Vanitas no Carte - The Case Study of Vanitas (2021)',
        thumbnail: 'assets/images/img-film/top film/HỒI KÍ VANITAS.jpg',
        backgroundImg: 'https://ecdn.game4v.com/g4v-content/uploads/2021/12/11080606/The-Case-Study-of-Vanitas-part-2-2-game4v-1639184762-96.png',
        view: 43000,
        episode: '14/24',
        date: 'wednesday',
        newEpisode: 15,
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: true,
        type: 'Anime, Hành động, Shounen, Siêu nhiên, Viễn tưởng',
        slugs: []
    },
    {
        filmName: 'Maiko-San Chi No Makanai-San',
        subTitle: 'Kimetsu No Yaiba ss2: Yuukaku-hen',
        thumbnail: 'assets/images/img-film/top film/MAIKO-SAN CHI NO MAKANAI-SAN.jpg',
        backgroundImg: 'https://i.ytimg.com/vi_webp/SZyuBw3dhOU/maxresdefault.webp',
        view: 14000,
        episode: '11/??',
        date: 'wednesday',
        newEpisode: 12,
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: false,
        type: 'Anime, Hành động, Shounen, Siêu nhiên, Viễn tưởng',
        slugs: []
    },
    {
        filmName: 'Saiyuuki Reload: Zeroin',
        subTitle: 'Saiyuuki Reload: Even a Worm Arc (2022)',
        thumbnail: 'assets/images/img-film/top film/SAIYUUKI RELOAD ZEROIN.jpg',
        backgroundImg: 'https://i0.wp.com/omnitos.com/wp-content/uploads/2022/01/Saiyuuki-Reload-Zeroin-Episode-3.jpg',
        view: 37000,
        episode: '04/??',
        date: 'wednesday',
        newEpisode: 5,
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: true,
        type: 'Anime, Hành động, Shounen, Siêu nhiên, Viễn tưởng',
        slugs: ["J_vPPFTiM", "CB7UzvEru", "W_UEcZ-Ar", "6p7shwNwAy", "HLyj03PES", "1Z8qNZAUO", "tc2UoagHe", "xjKEJtpQe", "sRm3e-pCS6", "ojXVx6J_", "kzosIraDu", "RPjVSqyal", "wWk2rXGIQ"]
    },
    {
        filmName: 'Maiko-San Chi No Makanai-San',
        subTitle: 'Kimetsu No Yaiba ss2: Yuukaku-hen',
        thumbnail: 'assets/images/img-film/top film/MAIKO-SAN CHI NO MAKANAI-SAN.jpg',
        backgroundImg: 'https://i.ytimg.com/vi_webp/SZyuBw3dhOU/maxresdefault.webp',
        view: 14000,
        episode: '12/??',
        date: 'thursday',
        newEpisode: 13,
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: false,
        type: 'Anime, Hành động, Shounen, Siêu nhiên, Viễn tưởng',
        slugs: []
    },
    {
        filmName: 'Nghịch Thiên Chí Tôn',
        subTitle: 'Nghịch Thiên Chí Tôn (2021)',
        thumbnail: 'assets/images/img-film/top film/NGHỊCH THIÊN CHÍ TÔN.jpg',
        backgroundImg: 'https://allimages.sgp1.digitaloceanspaces.com/tintapchicom/2021/08/Nghich-Thien-Chi-Ton-Tap-11-Vietsub-Thuyet-Minh.jpg',
        view: 98000,
        episode: '61/??',
        date: 'thursday',
        newEpisode: 62,
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: false,
        type: 'Anime, Hành động, Shounen, Siêu nhiên, Viễn tưởng',
        slugs: ["yUDFmuLe3", "jFzMq-INs", "w-HeuQkTJ", "ypP5G47WE", "mpn9Cls4e", "RYFaP-9_M"]
    },
    {
        filmName: 'Saiyuuki Reload: Zeroin',
        subTitle: 'Saiyuuki Reload: Even a Worm Arc (2022)',
        thumbnail: 'assets/images/img-film/top film/SAIYUUKI RELOAD ZEROIN.jpg',
        backgroundImg: 'https://i0.wp.com/omnitos.com/wp-content/uploads/2022/01/Saiyuuki-Reload-Zeroin-Episode-3.jpg',
        view: 98000,
        episode: '04/??',
        date: 'friday',
        newEpisode: 6,
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: false,
        type: 'Anime, Hành động, Shounen, Siêu nhiên, Viễn tưởng',
        slugs: ["J_vPPFTiM", "CB7UzvEru", "W_UEcZ-Ar", "6p7shwNwAy", "HLyj03PES", "1Z8qNZAUO", "tc2UoagHe", "xjKEJtpQe", "sRm3e-pCS6", "ojXVx6J_", "kzosIraDu", "RPjVSqyal", "wWk2rXGIQ"]
    },
    {
        filmName: 'Shingeki No Kyojin-The Final Season Part 2',
        subTitle: 'Shingeki no Kyojin Season 4, Attack on Titan Season 4 (2022)',
        thumbnail: 'assets/images/img-film/top film/SHINGEKI NO KYOJIN-THE FINAL SEASON PART 2.jpg',
        backgroundImg: 'https://animecorner.me/wp-content/uploads/2021/11/attack-on-titan-final-season-visual.png?ezimgfmt=ng%3Awebp%2Fngcb21%2Frs%3Adevice%2Frscb21-1',
        view: 90000,
        episode: '03/??',
        date: 'friday',
        newEpisode: 4,
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: false,
        type: 'Anime, Hành động, Shounen, Siêu nhiên, Viễn tưởng',
        slugs: ["R4MVqnpPh", "QEeqrnFO0", "ivkvp6ZC_R", "kKCOFXbf_", "Wlc7v_GC9", "nfkBiYDZt", "svzR7d _hy", "X7UeKtugw", "YwrdoVGs0", "qr2UwUrbb", "qT33PmnHmX", "my3ErMI5F"]
    },
    {
        filmName: 'Slow Loop',
        subTitle: 'Slow Loop (2022)',
        thumbnail: 'assets/images/img-film/top film/SLOW LOOP.jpg',
        backgroundImg: 'https://images3.alphacoders.com/121/thumb-1920-1213192.jpg',
        view: 30000,
        episode: '03/??',
        date: 'friday',
        newEpisode: 4,
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: false,
        type: 'Anime, Hành động, Shounen, Siêu nhiên, Viễn tưởng',
        slugs: []
    },
    {
        filmName: 'Thiếu Niên Ca Hành 2',
        subTitle: 'Thiếu Niên Ca Hành 2 (2021)',
        thumbnail: 'assets/images/img-film/top film/THIẾU NIÊN CA HÀNH 2.jpg',
        backgroundImg: 'https://ecdn.game4v.com/g4v-content/uploads/2021/06/gam4v-thieu-nien-ca-hanh.jpg',
        view: 96000,
        episode: '18/??',
        date: 'friday',
        newEpisode: 19,
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: false,
        type: 'Anime, Hành động, Shounen, Siêu nhiên, Viễn tưởng',
        slugs: []
    },
    {
        filmName: 'Yêu Thần Ký',
        subTitle: 'Yêu Thần Ký (2021)',
        thumbnail: 'assets/images/img-film/top film/YÊU THẦN KÝ.jpg',
        backgroundImg: 'https://zingaudio.net/wp-content/uploads/2020/10/yeu-than-ky.jpg',
        view: 46000,
        episode: '200/???',
        date: 'friday',
        newEpisode: 201,
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: false,
        type: 'Anime, Hành động, Shounen, Siêu nhiên, Viễn tưởng',
        slugs: []
    },
    {
        filmName: 'Ăn Không Uổng Kể Sơn Hải Kinh',
        subTitle: 'Ăn Không Uổng Kể Sơn Hải Kinh (2021)',
        thumbnail: 'assets/images/img-film/top film/ĂN KHÔNG UỔNG KỂ SƠN HẢI KINH.jpg',
        backgroundImg: 'https://pic.bstarstatic.com/ogv/07ec26b13704e80336a427abc3cdf3c3c5ad7471.png@960w_540h_1e_1c_1f.webp',
        view: 28000,
        date: 'saturday',
        newEpisode: 17,
        episode: '16/??',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: true,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: []
    },
    {
        filmName: 'Đấu La Đại Lục',
        subTitle: 'Đấu La Đại Lục – Soul Land',
        thumbnail: 'assets/images/img-film/top film/dau-la-dai-luc-1-250x350.jpg.webp',
        backgroundImg: 'https://ss-images.saostar.vn/2020/02/24/7047527/1_fxmws8sjy0fo5ehbehzyia.png',
        view: 37000,
        date: 'monday',
        newEpisode: 194,
        episode: '193/???',
        urlVideo: '',
        desc: 'Đấu La Đại Lục là một trong những tác phẩm đặc sắc của Đường Gia Tam Thiếu. Tác phẩm thuộc thể loại Huyễn Hiệp, mang đến cho độc giả một cái nhìn, một cảm nhận mới về thế giới hiệp khách huyền ảo. Câu chuyện với nhân vật chính, con một thợ rèn, một thợ rèn trở thành tửu quỷ, vì thê tử đã mất, sẵn sàng lôi cuốn người đọc ngay từ những chương đầu tiên. Đấu La Thế Giới, một đại lục rộng lớn, cư dân đông đúc. Chức nghiệp cao quý nhất tại đây được gọi là Hồn Sư. Mỗi người sinh ra, đều có một vũ hồn bẩm sinh. Vũ hồn có thể là cái cày, cái cuốc, liêm đao… thuộc khối công cụ, một đóa hoa cúc, một cành mai… thuộc thực vật hệ, đến các vũ hồn cường đại như Tuyết Ảnh Ma Hùng, Tật Phong Ma Lang….',
        bookmark: true,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: ["EF6c22eqR", "6USJTAQ90"]
    },
    {
        filmName: 'Phàm Nhân Tu Tiên',
        subTitle: 'Phàm Nhân Tu Tiên - Phong Khởi Thiên Nam (2020)',
        thumbnail: 'assets/images/img-film/top film/Phàm Nhân Tu Tiên.jpg',
        backgroundImg: 'https://i.ytimg.com/vi/uZgyf0p9WXk/maxresdefault.jpg',
        view: 36000,
        date: 'saturday',
        newEpisode: 35,
        episode: '34/??',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: true,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: []
    },
    {
        filmName: 'Tuyết Ưng Lĩnh Chủ Phần 3',
        subTitle: 'Tuyết Ưng Lĩnh Chủ Phần 3 (2021)',
        thumbnail: 'assets/images/img-film/top film/Tuyết Ưng Lĩnh Chủ Phần 3.jpg',
        backgroundImg: 'https://ecdn.game4v.com/g4v-content/uploads/2021/10/29151308/game4v-tuyet-ung-linh-chu-2-1635495188-92.jpg',
        view: 19000,
        date: 'sunday',
        newEpisode: 7,
        episode: '06/??',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: false,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: []
    },
    {
        filmName: 'Thôn Phệ Tinh Không',
        subTitle: 'Swallowed Star (2020)',
        thumbnail: 'assets/images/img-film/top film/Thôn Phệ Tinh Không.jpg',
        backgroundImg: 'https://img.subhay.net/date/info/Swallowed-Star-Nga-Cat-Tay-Hong-Thi-2.jpg',
        view: 21000,
        date: 'sunday',
        newEpisode: 33,
        episode: '32/??',
        urlVideo: '',
        desc: 'Mùa thứ 2 của anime Kimetsu No Yaiba xoay quanh arc khu phố đèn đỏ đội của Tanjiro cùng với âm trụ chiến đấu với 2 anh em thượng lục quỷ',
        bookmark: true,
        type: 'Anime, Hành động, Kinh dị, Siêu nhiên, Viễn tưởng',
        slugs: []
    },
];